// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: bank.proto

package bankpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BankService_CreateUser_FullMethodName            = "/bank.BankService/CreateUser"
	BankService_TransferMoney_FullMethodName         = "/bank.BankService/TransferMoney"
	BankService_GetBalance_FullMethodName            = "/bank.BankService/GetBalance"
	BankService_GetHistory_FullMethodName            = "/bank.BankService/GetHistory"
	BankService_CreateAdminSession_FullMethodName    = "/bank.BankService/CreateAdminSession"
	BankService_GetAdminOverview_FullMethodName      = "/bank.BankService/GetAdminOverview"
	BankService_ListAdminUsers_FullMethodName        = "/bank.BankService/ListAdminUsers"
	BankService_ListAdminUserAccounts_FullMethodName = "/bank.BankService/ListAdminUserAccounts"
	BankService_ListAdminTransactions_FullMethodName = "/bank.BankService/ListAdminTransactions"
	BankService_ListAdminAuditEvents_FullMethodName  = "/bank.BankService/ListAdminAuditEvents"
	BankService_ListAuditEvents_FullMethodName       = "/bank.BankService/ListAuditEvents"
)

// BankServiceClient is the client API for BankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BankService owns users, accounts, AP exchange validation, transfers,
// idempotency, audit events, and the hash-chain ledger.
type BankServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	TransferMoney(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	GetHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	// Read-only methods used by the Bank Admin API through the Gateway.
	CreateAdminSession(ctx context.Context, in *CreateAdminSessionRequest, opts ...grpc.CallOption) (*CreateAdminSessionResponse, error)
	GetAdminOverview(ctx context.Context, in *AdminOverviewRequest, opts ...grpc.CallOption) (*AdminOverviewResponse, error)
	ListAdminUsers(ctx context.Context, in *ListAdminUsersRequest, opts ...grpc.CallOption) (*ListAdminUsersResponse, error)
	ListAdminUserAccounts(ctx context.Context, in *ListAdminUserAccountsRequest, opts ...grpc.CallOption) (*ListAdminUserAccountsResponse, error)
	ListAdminTransactions(ctx context.Context, in *ListAdminTransactionsRequest, opts ...grpc.CallOption) (*ListAdminTransactionsResponse, error)
	ListAdminAuditEvents(ctx context.Context, in *ListAdminAuditEventsRequest, opts ...grpc.CallOption) (*ListAdminAuditEventsResponse, error)
	// Admin dashboard read-only audit log listing. Trust boundary: this RPC is
	// only reachable on the internal TLS gRPC network; admin authn/authz happens
	// at the API Gateway before it forwards the call.
	ListAuditEvents(ctx context.Context, in *ListAuditEventsRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error)
}

type bankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankServiceClient(cc grpc.ClientConnInterface) BankServiceClient {
	return &bankServiceClient{cc}
}

func (c *bankServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, BankService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) TransferMoney(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, BankService_TransferMoney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, BankService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) GetHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, BankService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) CreateAdminSession(ctx context.Context, in *CreateAdminSessionRequest, opts ...grpc.CallOption) (*CreateAdminSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdminSessionResponse)
	err := c.cc.Invoke(ctx, BankService_CreateAdminSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) GetAdminOverview(ctx context.Context, in *AdminOverviewRequest, opts ...grpc.CallOption) (*AdminOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminOverviewResponse)
	err := c.cc.Invoke(ctx, BankService_GetAdminOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) ListAdminUsers(ctx context.Context, in *ListAdminUsersRequest, opts ...grpc.CallOption) (*ListAdminUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminUsersResponse)
	err := c.cc.Invoke(ctx, BankService_ListAdminUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) ListAdminUserAccounts(ctx context.Context, in *ListAdminUserAccountsRequest, opts ...grpc.CallOption) (*ListAdminUserAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminUserAccountsResponse)
	err := c.cc.Invoke(ctx, BankService_ListAdminUserAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) ListAdminTransactions(ctx context.Context, in *ListAdminTransactionsRequest, opts ...grpc.CallOption) (*ListAdminTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminTransactionsResponse)
	err := c.cc.Invoke(ctx, BankService_ListAdminTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) ListAdminAuditEvents(ctx context.Context, in *ListAdminAuditEventsRequest, opts ...grpc.CallOption) (*ListAdminAuditEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminAuditEventsResponse)
	err := c.cc.Invoke(ctx, BankService_ListAdminAuditEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) ListAuditEvents(ctx context.Context, in *ListAuditEventsRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditEventsResponse)
	err := c.cc.Invoke(ctx, BankService_ListAuditEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankServiceServer is the server API for BankService service.
// All implementations must embed UnimplementedBankServiceServer
// for forward compatibility.
//
// BankService owns users, accounts, AP exchange validation, transfers,
// idempotency, audit events, and the hash-chain ledger.
type BankServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	TransferMoney(context.Context, *TransferRequest) (*TransferResponse, error)
	GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	GetHistory(context.Context, *HistoryRequest) (*HistoryResponse, error)
	// Read-only methods used by the Bank Admin API through the Gateway.
	CreateAdminSession(context.Context, *CreateAdminSessionRequest) (*CreateAdminSessionResponse, error)
	GetAdminOverview(context.Context, *AdminOverviewRequest) (*AdminOverviewResponse, error)
	ListAdminUsers(context.Context, *ListAdminUsersRequest) (*ListAdminUsersResponse, error)
	ListAdminUserAccounts(context.Context, *ListAdminUserAccountsRequest) (*ListAdminUserAccountsResponse, error)
	ListAdminTransactions(context.Context, *ListAdminTransactionsRequest) (*ListAdminTransactionsResponse, error)
	ListAdminAuditEvents(context.Context, *ListAdminAuditEventsRequest) (*ListAdminAuditEventsResponse, error)
	// Admin dashboard read-only audit log listing. Trust boundary: this RPC is
	// only reachable on the internal TLS gRPC network; admin authn/authz happens
	// at the API Gateway before it forwards the call.
	ListAuditEvents(context.Context, *ListAuditEventsRequest) (*ListAuditEventsResponse, error)
	mustEmbedUnimplementedBankServiceServer()
}

// UnimplementedBankServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankServiceServer struct{}

func (UnimplementedBankServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedBankServiceServer) TransferMoney(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferMoney not implemented")
}
func (UnimplementedBankServiceServer) GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedBankServiceServer) GetHistory(context.Context, *HistoryRequest) (*HistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedBankServiceServer) CreateAdminSession(context.Context, *CreateAdminSessionRequest) (*CreateAdminSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdminSession not implemented")
}
func (UnimplementedBankServiceServer) GetAdminOverview(context.Context, *AdminOverviewRequest) (*AdminOverviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminOverview not implemented")
}
func (UnimplementedBankServiceServer) ListAdminUsers(context.Context, *ListAdminUsersRequest) (*ListAdminUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminUsers not implemented")
}
func (UnimplementedBankServiceServer) ListAdminUserAccounts(context.Context, *ListAdminUserAccountsRequest) (*ListAdminUserAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminUserAccounts not implemented")
}
func (UnimplementedBankServiceServer) ListAdminTransactions(context.Context, *ListAdminTransactionsRequest) (*ListAdminTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminTransactions not implemented")
}
func (UnimplementedBankServiceServer) ListAdminAuditEvents(context.Context, *ListAdminAuditEventsRequest) (*ListAdminAuditEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminAuditEvents not implemented")
}
func (UnimplementedBankServiceServer) ListAuditEvents(context.Context, *ListAuditEventsRequest) (*ListAuditEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditEvents not implemented")
}
func (UnimplementedBankServiceServer) mustEmbedUnimplementedBankServiceServer() {}
func (UnimplementedBankServiceServer) testEmbeddedByValue()                     {}

// UnsafeBankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankServiceServer will
// result in compilation errors.
type UnsafeBankServiceServer interface {
	mustEmbedUnimplementedBankServiceServer()
}

func RegisterBankServiceServer(s grpc.ServiceRegistrar, srv BankServiceServer) {
	// If the following call panics, it indicates UnimplementedBankServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BankService_ServiceDesc, srv)
}

func _BankService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_TransferMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).TransferMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_TransferMoney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).TransferMoney(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).GetBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).GetHistory(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_CreateAdminSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).CreateAdminSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_CreateAdminSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).CreateAdminSession(ctx, req.(*CreateAdminSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_GetAdminOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).GetAdminOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_GetAdminOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).GetAdminOverview(ctx, req.(*AdminOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_ListAdminUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).ListAdminUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_ListAdminUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).ListAdminUsers(ctx, req.(*ListAdminUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_ListAdminUserAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminUserAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).ListAdminUserAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_ListAdminUserAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).ListAdminUserAccounts(ctx, req.(*ListAdminUserAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_ListAdminTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).ListAdminTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_ListAdminTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).ListAdminTransactions(ctx, req.(*ListAdminTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_ListAdminAuditEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminAuditEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).ListAdminAuditEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_ListAdminAuditEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).ListAdminAuditEvents(ctx, req.(*ListAdminAuditEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_ListAuditEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).ListAuditEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_ListAuditEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).ListAuditEvents(ctx, req.(*ListAuditEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BankService_ServiceDesc is the grpc.ServiceDesc for BankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bank.BankService",
	HandlerType: (*BankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _BankService_CreateUser_Handler,
		},
		{
			MethodName: "TransferMoney",
			Handler:    _BankService_TransferMoney_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _BankService_GetBalance_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _BankService_GetHistory_Handler,
		},
		{
			MethodName: "CreateAdminSession",
			Handler:    _BankService_CreateAdminSession_Handler,
		},
		{
			MethodName: "GetAdminOverview",
			Handler:    _BankService_GetAdminOverview_Handler,
		},
		{
			MethodName: "ListAdminUsers",
			Handler:    _BankService_ListAdminUsers_Handler,
		},
		{
			MethodName: "ListAdminUserAccounts",
			Handler:    _BankService_ListAdminUserAccounts_Handler,
		},
		{
			MethodName: "ListAdminTransactions",
			Handler:    _BankService_ListAdminTransactions_Handler,
		},
		{
			MethodName: "ListAdminAuditEvents",
			Handler:    _BankService_ListAdminAuditEvents_Handler,
		},
		{
			MethodName: "ListAuditEvents",
			Handler:    _BankService_ListAuditEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bank.proto",
}
