// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: kdc.proto

package kdcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KDCService_RequestTGT_FullMethodName           = "/kdc.KDCService/RequestTGT"
	KDCService_RequestServiceTicket_FullMethodName = "/kdc.KDCService/RequestServiceTicket"
)

// KDCServiceClient is the client API for KDCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// @title KDC Service (Key Distribution Center)
// @author Tran Nguyen Tri Thanh (tntt)
// @summary Processing AS Exchange and TGS Exchange using a Kerberos hybrid model.
type KDCServiceClient interface {
	// *
	// @description Phase 2: AS Exchange — Client authenticates and receives a Ticket-Granting Ticket (TGT).
	// @param {ASRequest} request - Contains client ID, target TGS ID, and parameters to prevent replay attacks.
	// @returns {ASResponse} Encrypted payload containing the Session Key and the TGT.
	RequestTGT(ctx context.Context, in *ASRequest, opts ...grpc.CallOption) (*ASResponse, error)
	// *
	// @description Phase 3: TGS Exchange — Client uses the TGT to request a Service Ticket for a specific service.
	// @param {TGSRequest} request - Contains the target service ID, the TGT, and the client's authenticator.
	// @returns {TGSResponse} Encrypted payload containing the Service Ticket and the Client-Service Session Key.
	RequestServiceTicket(ctx context.Context, in *TGSRequest, opts ...grpc.CallOption) (*TGSResponse, error)
}

type kDCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKDCServiceClient(cc grpc.ClientConnInterface) KDCServiceClient {
	return &kDCServiceClient{cc}
}

func (c *kDCServiceClient) RequestTGT(ctx context.Context, in *ASRequest, opts ...grpc.CallOption) (*ASResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ASResponse)
	err := c.cc.Invoke(ctx, KDCService_RequestTGT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kDCServiceClient) RequestServiceTicket(ctx context.Context, in *TGSRequest, opts ...grpc.CallOption) (*TGSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TGSResponse)
	err := c.cc.Invoke(ctx, KDCService_RequestServiceTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KDCServiceServer is the server API for KDCService service.
// All implementations must embed UnimplementedKDCServiceServer
// for forward compatibility.
//
// *
// @title KDC Service (Key Distribution Center)
// @author Tran Nguyen Tri Thanh (tntt)
// @summary Processing AS Exchange and TGS Exchange using a Kerberos hybrid model.
type KDCServiceServer interface {
	// *
	// @description Phase 2: AS Exchange — Client authenticates and receives a Ticket-Granting Ticket (TGT).
	// @param {ASRequest} request - Contains client ID, target TGS ID, and parameters to prevent replay attacks.
	// @returns {ASResponse} Encrypted payload containing the Session Key and the TGT.
	RequestTGT(context.Context, *ASRequest) (*ASResponse, error)
	// *
	// @description Phase 3: TGS Exchange — Client uses the TGT to request a Service Ticket for a specific service.
	// @param {TGSRequest} request - Contains the target service ID, the TGT, and the client's authenticator.
	// @returns {TGSResponse} Encrypted payload containing the Service Ticket and the Client-Service Session Key.
	RequestServiceTicket(context.Context, *TGSRequest) (*TGSResponse, error)
	mustEmbedUnimplementedKDCServiceServer()
}

// UnimplementedKDCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKDCServiceServer struct{}

func (UnimplementedKDCServiceServer) RequestTGT(context.Context, *ASRequest) (*ASResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestTGT not implemented")
}
func (UnimplementedKDCServiceServer) RequestServiceTicket(context.Context, *TGSRequest) (*TGSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestServiceTicket not implemented")
}
func (UnimplementedKDCServiceServer) mustEmbedUnimplementedKDCServiceServer() {}
func (UnimplementedKDCServiceServer) testEmbeddedByValue()                    {}

// UnsafeKDCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KDCServiceServer will
// result in compilation errors.
type UnsafeKDCServiceServer interface {
	mustEmbedUnimplementedKDCServiceServer()
}

func RegisterKDCServiceServer(s grpc.ServiceRegistrar, srv KDCServiceServer) {
	// If the following call panics, it indicates UnimplementedKDCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KDCService_ServiceDesc, srv)
}

func _KDCService_RequestTGT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ASRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KDCServiceServer).RequestTGT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KDCService_RequestTGT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KDCServiceServer).RequestTGT(ctx, req.(*ASRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KDCService_RequestServiceTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TGSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KDCServiceServer).RequestServiceTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KDCService_RequestServiceTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KDCServiceServer).RequestServiceTicket(ctx, req.(*TGSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KDCService_ServiceDesc is the grpc.ServiceDesc for KDCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KDCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kdc.KDCService",
	HandlerType: (*KDCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestTGT",
			Handler:    _KDCService_RequestTGT_Handler,
		},
		{
			MethodName: "RequestServiceTicket",
			Handler:    _KDCService_RequestServiceTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kdc.proto",
}
