#!/usr/bin/env bash
#
# gen-certs.sh — Generate the gRPC transport TLS material for the mini-banking stack.
#
# Layout produced:
#   1. Reuse provisioned gRPC Transport CA -> ca-service/certs/intermediate/grpc-ca.{crt,key}
#   2. KDC service  gRPC server cert       -> kdc-service/certs/kdc-server.{crt,key}
#   2b. KDC AS_REP signing cert (identity)  -> kdc-service/certs/kdc-signing.crt
#         + chain bundle (leaf + Client CA) -> kdc-service/certs/kdc-signing-chain.pem
#         Reuses the existing kdc-private.pem (the key the KDC signs AS_REP with),
#         signed by the Client CA so the client can verify it chains to the Root CA.
#   3. Bank service gRPC server cert       -> banking-service/certs/grpc/bank-server.{crt,key}
#   4. CA service gRPC cert is generated by provisioning and signed by the same gRPC Transport CA:
#        cd ca-service && go run ./scripts/provision_ca_dev.go
#   5. Trust anchors are distributed to every party that must verify a server:
#        - api-gateway/certs/grpc-ca.crt     (gRPC Transport CA + Root CA bundle)
#        - kdc-service/certs/grpc-ca.crt     (gRPC Transport CA + Root CA bundle)
#        - banking-service/certs/grpc/grpc-ca.crt (gRPC Transport CA + Root CA bundle)
#
# Usage:
#   ./gen-certs.sh            # 825-day certs
#   DAYS=90 ./gen-certs.sh    # override validity
#
set -euo pipefail

# On Git-bash / MSYS (Windows) a leading-slash argument like -subj "/C=VN/..." is
# rewritten into a Windows path (e.g. "C:/Program Files/Git/C=VN/..."), which makes
# openssl reject the subject. Exclude only the subject (it always starts with /C=)
# from conversion so real file-path arguments are still translated correctly.
# This variable is inert on Linux/macOS.
export MSYS2_ARG_CONV_EXCL='/C='

# --- locate repo root (this script lives in <root>/scripts/gen-certs) ----------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DAYS="${DAYS:-825}"

GRPC_CA_CRT="$ROOT/ca-service/certs/intermediate/grpc-ca.crt"
GRPC_CA_KEY="$ROOT/ca-service/certs/intermediate/grpc-ca.key"
ROOT_CA_CRT="$ROOT/ca-service/certs/root-ca/ca.crt"
CA_SERVER_CRT="$ROOT/ca-service/certs/grpc/ca-server.crt"
CLIENT_CA_CRT="$ROOT/ca-service/certs/intermediate/client-ca.crt"
CLIENT_CA_KEY="$ROOT/ca-service/certs/intermediate/client-ca.key"
KDC_PRIV_KEY="$ROOT/kdc-service/certs/kdc-private.pem"

echo "==> Reusing provisioned gRPC Transport CA"
if [[ ! -f "$GRPC_CA_CRT" || ! -f "$GRPC_CA_KEY" || ! -f "$ROOT_CA_CRT" || ! -f "$CA_SERVER_CRT" ]]; then
  cat >&2 <<EOF
Missing provisioned gRPC Transport CA or CA Service server cert.
Expected:
  $GRPC_CA_CRT
  $GRPC_CA_KEY
  $ROOT_CA_CRT
  $CA_SERVER_CRT

Run this first:
  cd "$ROOT/ca-service"
  ROOT_CA_KEY_PASSWORD=<dev-password> go run ./scripts/provision_ca_dev.go
EOF
  exit 1
fi

# gen_server <name> <cn> <san-csv> <dest-crt> <dest-key>
gen_server() {
  local name="$1" cn="$2" sans="$3" dest_crt="$4" dest_key="$5"
  local tmp; tmp="$(mktemp -d)"

  echo "==> $name server certificate (CN=$cn)"
  openssl genrsa -out "$tmp/srv.key" 2048
  openssl req -new -key "$tmp/srv.key" -subj "/C=VN/O=Mini_App_Banking/CN=$cn" -out "$tmp/srv.csr"

  printf 'subjectAltName=%s\nextendedKeyUsage=serverAuth\nkeyUsage=digitalSignature,keyEncipherment\n' "$sans" > "$tmp/ext.cnf"

  openssl x509 -req -in "$tmp/srv.csr" \
    -CA "$GRPC_CA_CRT" -CAkey "$GRPC_CA_KEY" -CAcreateserial \
    -days "$DAYS" -sha256 -extfile "$tmp/ext.cnf" -out "$tmp/srv.crt"

  mkdir -p "$(dirname "$dest_crt")" "$(dirname "$dest_key")"
  cp "$tmp/srv.crt" "$dest_crt"
  cp "$tmp/srv.key" "$dest_key"
  echo "    -> $dest_crt"
  rm -rf "$tmp"
}

# gen_kdc_signing_cert issues the identity cert the KDC uses to sign AS_REP.
# Unlike gen_server it does NOT mint a fresh key: it reuses the existing
# kdc-private.pem (the exact key the KDC loads to sign), wraps its public key in a
# leaf cert signed by the Client CA, and writes a chain bundle (leaf + Client CA)
# so the browser can verify AS_REP chains to the embedded Root CA.
gen_kdc_signing_cert() {
  if [[ ! -f "$KDC_PRIV_KEY" || ! -f "$CLIENT_CA_CRT" || ! -f "$CLIENT_CA_KEY" ]]; then
    cat >&2 <<EOF
Missing KDC signing key or Client CA. Expected:
  $KDC_PRIV_KEY
  $CLIENT_CA_CRT
  $CLIENT_CA_KEY

Run these first from runtime root:
  cd "$ROOT"
  (cd ca-service && go run ./scripts/provision_ca_dev.go)
  go run ./kdc-service/scripts/provision_kdc_dev.go
Then run:
  ./scripts/gen-certs/gen-certs.sh
EOF
    exit 1
  fi

  local tmp; tmp="$(mktemp -d)"
  local leaf="$ROOT/kdc-service/certs/kdc-signing.crt"
  local chain="$ROOT/kdc-service/certs/kdc-signing-chain.pem"

  echo "==> KDC AS_REP signing certificate (CN=kdc-service, issued by Client CA)"
  openssl req -new -key "$KDC_PRIV_KEY" -subj "/C=VN/O=Mini_App_Banking/CN=kdc-service" -out "$tmp/kdc.csr"
  printf 'basicConstraints=CA:FALSE\nkeyUsage=digitalSignature\n' > "$tmp/ext.cnf"
  openssl x509 -req -in "$tmp/kdc.csr" \
    -CA "$CLIENT_CA_CRT" -CAkey "$CLIENT_CA_KEY" -CAcreateserial \
    -days "$DAYS" -sha256 -extfile "$tmp/ext.cnf" -out "$leaf"

  # Chain bundle = signing leaf first, then the Client CA intermediate.
  cat "$leaf" "$CLIENT_CA_CRT" > "$chain"
  echo "    -> $leaf"
  echo "    -> $chain"
  rm -rf "$tmp"
}

gen_server "KDC"  "kdc-service" \
  "DNS:kdc-service,DNS:localhost,IP:127.0.0.1" \
  "$ROOT/kdc-service/certs/kdc-server.crt" \
  "$ROOT/kdc-service/certs/kdc-server.key"

gen_kdc_signing_cert

gen_server "Bank" "banking-service" \
  "DNS:banking-service,DNS:bank-service,DNS:localhost,IP:127.0.0.1" \
  "$ROOT/banking-service/certs/grpc/bank-server.crt" \
  "$ROOT/banking-service/certs/grpc/bank-server.key"

echo "==> Distributing transport trust bundles to verifiers"
distribute_bundle() { mkdir -p "$(dirname "$1")"; cat "$GRPC_CA_CRT" "$ROOT_CA_CRT" > "$1"; echo "    -> $1"; }
distribute_bundle "$ROOT/api-gateway/certs/grpc-ca.crt"
distribute_bundle "$ROOT/kdc-service/certs/grpc-ca.crt"
# Must live inside certs/grpc/ — docker-compose mounts ./banking-service/certs/grpc
distribute_bundle "$ROOT/banking-service/certs/grpc/grpc-ca.crt"
rm -f "$ROOT/kdc-service/certs/grpc/ca-server-ca.crt" \
      "$ROOT/banking-service/certs/grpc-ca.crt"

# Root CA (trust anchor) cho frontend — nạp runtime tại /trust/root-ca.pem, phục vụ
# same-origin bởi SPA (KHÔNG qua gateway). Đặt trong public/ để Vite serve tĩnh.
echo "==> Distributing Root CA trust anchor to frontend"
mkdir -p "$ROOT/frontend/public/trust"
cp "$ROOT_CA_CRT" "$ROOT/frontend/public/trust/root-ca.pem"
echo "    -> $ROOT/frontend/public/trust/root-ca.pem"

echo
echo "Done. KDC/Bank certs valid for $DAYS days. gRPC Transport CA private key kept in $GRPC_CA_KEY."
echo "Set the gateway CA_CERT_PATH to api-gateway/certs/grpc-ca.crt (transport trust bundle)."
