// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: kdc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "kdc";

/** @description Request payload for the Authentication Service (AS) Exchange. */
export interface ASRequest {
  clientId: string;
  tgsId: string;
  nonce1: Buffer;
  timestamp: number;
  certSn: string;
  preAuthSignature: Buffer;
}

/**
 * @description Response payload for the Authentication Service (AS) Exchange.
 * @note AS_REP = E_{pub_c}[ K_{c,tgs} || TGT || Nonce1 || TS ]
 * @note TGT = E_{K_tgs}[ client_id, client_ip, K_{c,tgs}, expiry ]
 * @note TTL default is 30 minutes
 */
export interface ASResponse {
  encryptedPayload: Buffer;
  tgtExpiryUnix: number;
}

/**
 * @description Request payload for the Ticket-Granting Service (TGS) Exchange.
 * @note Auth_c = E_{K_{c,tgs}}[ client_id, TS, Nonce2 ]
 */
export interface TGSRequest {
  serviceId: string;
  tgtCiphertext: Buffer;
  authenticator: Buffer;
  certSn: string;
  nonce2: Buffer;
  requestedScope: string;
}

/**
 * @description Response payload for the Ticket-Granting Service (TGS) Exchange.
 * @note TGS_REP = E_{K_{c,tgs}}[ K_{c,v} || Ticket_v || Nonce2 ]
 * @note Ticket_v = E_{K_v}[ client_id, K_{c,v}, pub_c_pem, expiry ]
 */
export interface TGSResponse {
  encryptedPayload: Buffer;
  ticketExpiryUnix: number;
}

function createBaseASRequest(): ASRequest {
  return {
    clientId: "",
    tgsId: "",
    nonce1: Buffer.alloc(0),
    timestamp: 0,
    certSn: "",
    preAuthSignature: Buffer.alloc(0),
  };
}

export const ASRequest: MessageFns<ASRequest> = {
  encode(message: ASRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientId !== "") {
      writer.uint32(10).string(message.clientId);
    }
    if (message.tgsId !== "") {
      writer.uint32(18).string(message.tgsId);
    }
    if (message.nonce1.length !== 0) {
      writer.uint32(26).bytes(message.nonce1);
    }
    if (message.timestamp !== 0) {
      writer.uint32(32).int64(message.timestamp);
    }
    if (message.certSn !== "") {
      writer.uint32(42).string(message.certSn);
    }
    if (message.preAuthSignature.length !== 0) {
      writer.uint32(50).bytes(message.preAuthSignature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ASRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseASRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tgsId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nonce1 = Buffer.from(reader.bytes());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.certSn = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.preAuthSignature = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ASRequest {
    return {
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      tgsId: isSet(object.tgsId)
        ? globalThis.String(object.tgsId)
        : isSet(object.tgs_id)
        ? globalThis.String(object.tgs_id)
        : "",
      nonce1: isSet(object.nonce1) ? Buffer.from(bytesFromBase64(object.nonce1)) : Buffer.alloc(0),
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      certSn: isSet(object.certSn)
        ? globalThis.String(object.certSn)
        : isSet(object.cert_sn)
        ? globalThis.String(object.cert_sn)
        : "",
      preAuthSignature: isSet(object.preAuthSignature)
        ? Buffer.from(bytesFromBase64(object.preAuthSignature))
        : isSet(object.pre_auth_signature)
        ? Buffer.from(bytesFromBase64(object.pre_auth_signature))
        : Buffer.alloc(0),
    };
  },

  toJSON(message: ASRequest): unknown {
    const obj: any = {};
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.tgsId !== "") {
      obj.tgsId = message.tgsId;
    }
    if (message.nonce1.length !== 0) {
      obj.nonce1 = base64FromBytes(message.nonce1);
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.certSn !== "") {
      obj.certSn = message.certSn;
    }
    if (message.preAuthSignature.length !== 0) {
      obj.preAuthSignature = base64FromBytes(message.preAuthSignature);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ASRequest>, I>>(base?: I): ASRequest {
    return ASRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ASRequest>, I>>(object: I): ASRequest {
    const message = createBaseASRequest();
    message.clientId = object.clientId ?? "";
    message.tgsId = object.tgsId ?? "";
    message.nonce1 = object.nonce1 ?? Buffer.alloc(0);
    message.timestamp = object.timestamp ?? 0;
    message.certSn = object.certSn ?? "";
    message.preAuthSignature = object.preAuthSignature ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseASResponse(): ASResponse {
  return { encryptedPayload: Buffer.alloc(0), tgtExpiryUnix: 0 };
}

export const ASResponse: MessageFns<ASResponse> = {
  encode(message: ASResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.encryptedPayload.length !== 0) {
      writer.uint32(10).bytes(message.encryptedPayload);
    }
    if (message.tgtExpiryUnix !== 0) {
      writer.uint32(16).int64(message.tgtExpiryUnix);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ASResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseASResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.encryptedPayload = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tgtExpiryUnix = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ASResponse {
    return {
      encryptedPayload: isSet(object.encryptedPayload)
        ? Buffer.from(bytesFromBase64(object.encryptedPayload))
        : isSet(object.encrypted_payload)
        ? Buffer.from(bytesFromBase64(object.encrypted_payload))
        : Buffer.alloc(0),
      tgtExpiryUnix: isSet(object.tgtExpiryUnix)
        ? globalThis.Number(object.tgtExpiryUnix)
        : isSet(object.tgt_expiry_unix)
        ? globalThis.Number(object.tgt_expiry_unix)
        : 0,
    };
  },

  toJSON(message: ASResponse): unknown {
    const obj: any = {};
    if (message.encryptedPayload.length !== 0) {
      obj.encryptedPayload = base64FromBytes(message.encryptedPayload);
    }
    if (message.tgtExpiryUnix !== 0) {
      obj.tgtExpiryUnix = Math.round(message.tgtExpiryUnix);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ASResponse>, I>>(base?: I): ASResponse {
    return ASResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ASResponse>, I>>(object: I): ASResponse {
    const message = createBaseASResponse();
    message.encryptedPayload = object.encryptedPayload ?? Buffer.alloc(0);
    message.tgtExpiryUnix = object.tgtExpiryUnix ?? 0;
    return message;
  },
};

function createBaseTGSRequest(): TGSRequest {
  return {
    serviceId: "",
    tgtCiphertext: Buffer.alloc(0),
    authenticator: Buffer.alloc(0),
    certSn: "",
    nonce2: Buffer.alloc(0),
    requestedScope: "",
  };
}

export const TGSRequest: MessageFns<TGSRequest> = {
  encode(message: TGSRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serviceId !== "") {
      writer.uint32(10).string(message.serviceId);
    }
    if (message.tgtCiphertext.length !== 0) {
      writer.uint32(18).bytes(message.tgtCiphertext);
    }
    if (message.authenticator.length !== 0) {
      writer.uint32(26).bytes(message.authenticator);
    }
    if (message.certSn !== "") {
      writer.uint32(34).string(message.certSn);
    }
    if (message.nonce2.length !== 0) {
      writer.uint32(42).bytes(message.nonce2);
    }
    if (message.requestedScope !== "") {
      writer.uint32(50).string(message.requestedScope);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TGSRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTGSRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serviceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tgtCiphertext = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.authenticator = Buffer.from(reader.bytes());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.certSn = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.nonce2 = Buffer.from(reader.bytes());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.requestedScope = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TGSRequest {
    return {
      serviceId: isSet(object.serviceId)
        ? globalThis.String(object.serviceId)
        : isSet(object.service_id)
        ? globalThis.String(object.service_id)
        : "",
      tgtCiphertext: isSet(object.tgtCiphertext)
        ? Buffer.from(bytesFromBase64(object.tgtCiphertext))
        : isSet(object.tgt_ciphertext)
        ? Buffer.from(bytesFromBase64(object.tgt_ciphertext))
        : Buffer.alloc(0),
      authenticator: isSet(object.authenticator) ? Buffer.from(bytesFromBase64(object.authenticator)) : Buffer.alloc(0),
      certSn: isSet(object.certSn)
        ? globalThis.String(object.certSn)
        : isSet(object.cert_sn)
        ? globalThis.String(object.cert_sn)
        : "",
      nonce2: isSet(object.nonce2) ? Buffer.from(bytesFromBase64(object.nonce2)) : Buffer.alloc(0),
      requestedScope: isSet(object.requestedScope)
        ? globalThis.String(object.requestedScope)
        : isSet(object.requested_scope)
        ? globalThis.String(object.requested_scope)
        : "",
    };
  },

  toJSON(message: TGSRequest): unknown {
    const obj: any = {};
    if (message.serviceId !== "") {
      obj.serviceId = message.serviceId;
    }
    if (message.tgtCiphertext.length !== 0) {
      obj.tgtCiphertext = base64FromBytes(message.tgtCiphertext);
    }
    if (message.authenticator.length !== 0) {
      obj.authenticator = base64FromBytes(message.authenticator);
    }
    if (message.certSn !== "") {
      obj.certSn = message.certSn;
    }
    if (message.nonce2.length !== 0) {
      obj.nonce2 = base64FromBytes(message.nonce2);
    }
    if (message.requestedScope !== "") {
      obj.requestedScope = message.requestedScope;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TGSRequest>, I>>(base?: I): TGSRequest {
    return TGSRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TGSRequest>, I>>(object: I): TGSRequest {
    const message = createBaseTGSRequest();
    message.serviceId = object.serviceId ?? "";
    message.tgtCiphertext = object.tgtCiphertext ?? Buffer.alloc(0);
    message.authenticator = object.authenticator ?? Buffer.alloc(0);
    message.certSn = object.certSn ?? "";
    message.nonce2 = object.nonce2 ?? Buffer.alloc(0);
    message.requestedScope = object.requestedScope ?? "";
    return message;
  },
};

function createBaseTGSResponse(): TGSResponse {
  return { encryptedPayload: Buffer.alloc(0), ticketExpiryUnix: 0 };
}

export const TGSResponse: MessageFns<TGSResponse> = {
  encode(message: TGSResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.encryptedPayload.length !== 0) {
      writer.uint32(10).bytes(message.encryptedPayload);
    }
    if (message.ticketExpiryUnix !== 0) {
      writer.uint32(16).int64(message.ticketExpiryUnix);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TGSResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTGSResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.encryptedPayload = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ticketExpiryUnix = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TGSResponse {
    return {
      encryptedPayload: isSet(object.encryptedPayload)
        ? Buffer.from(bytesFromBase64(object.encryptedPayload))
        : isSet(object.encrypted_payload)
        ? Buffer.from(bytesFromBase64(object.encrypted_payload))
        : Buffer.alloc(0),
      ticketExpiryUnix: isSet(object.ticketExpiryUnix)
        ? globalThis.Number(object.ticketExpiryUnix)
        : isSet(object.ticket_expiry_unix)
        ? globalThis.Number(object.ticket_expiry_unix)
        : 0,
    };
  },

  toJSON(message: TGSResponse): unknown {
    const obj: any = {};
    if (message.encryptedPayload.length !== 0) {
      obj.encryptedPayload = base64FromBytes(message.encryptedPayload);
    }
    if (message.ticketExpiryUnix !== 0) {
      obj.ticketExpiryUnix = Math.round(message.ticketExpiryUnix);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TGSResponse>, I>>(base?: I): TGSResponse {
    return TGSResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TGSResponse>, I>>(object: I): TGSResponse {
    const message = createBaseTGSResponse();
    message.encryptedPayload = object.encryptedPayload ?? Buffer.alloc(0);
    message.ticketExpiryUnix = object.ticketExpiryUnix ?? 0;
    return message;
  },
};

/**
 * @title KDC Service (Key Distribution Center)
 * @author Tran Nguyen Tri Thanh (tntt)
 * @summary Processing AS Exchange and TGS Exchange using a Kerberos hybrid model.
 */
export type KDCServiceService = typeof KDCServiceService;
export const KDCServiceService = {
  /**
   * @description Phase 2: AS Exchange — Client authenticates and receives a Ticket-Granting Ticket (TGT).
   * @param {ASRequest} request - Contains client ID, target TGS ID, and parameters to prevent replay attacks.
   * @returns {ASResponse} Encrypted payload containing the Session Key and the TGT.
   */
  requestTgt: {
    path: "/kdc.KDCService/RequestTGT" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ASRequest): Buffer => Buffer.from(ASRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ASRequest => ASRequest.decode(value),
    responseSerialize: (value: ASResponse): Buffer => Buffer.from(ASResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ASResponse => ASResponse.decode(value),
  },
  /**
   * @description Phase 3: TGS Exchange — Client uses the TGT to request a Service Ticket for a specific service.
   * @param {TGSRequest} request - Contains the target service ID, the TGT, and the client's authenticator.
   * @returns {TGSResponse} Encrypted payload containing the Service Ticket and the Client-Service Session Key.
   */
  requestServiceTicket: {
    path: "/kdc.KDCService/RequestServiceTicket" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: TGSRequest): Buffer => Buffer.from(TGSRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): TGSRequest => TGSRequest.decode(value),
    responseSerialize: (value: TGSResponse): Buffer => Buffer.from(TGSResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): TGSResponse => TGSResponse.decode(value),
  },
} as const;

export interface KDCServiceServer extends UntypedServiceImplementation {
  /**
   * @description Phase 2: AS Exchange — Client authenticates and receives a Ticket-Granting Ticket (TGT).
   * @param {ASRequest} request - Contains client ID, target TGS ID, and parameters to prevent replay attacks.
   * @returns {ASResponse} Encrypted payload containing the Session Key and the TGT.
   */
  requestTgt: handleUnaryCall<ASRequest, ASResponse>;
  /**
   * @description Phase 3: TGS Exchange — Client uses the TGT to request a Service Ticket for a specific service.
   * @param {TGSRequest} request - Contains the target service ID, the TGT, and the client's authenticator.
   * @returns {TGSResponse} Encrypted payload containing the Service Ticket and the Client-Service Session Key.
   */
  requestServiceTicket: handleUnaryCall<TGSRequest, TGSResponse>;
}

export interface KDCServiceClient extends Client {
  /**
   * @description Phase 2: AS Exchange — Client authenticates and receives a Ticket-Granting Ticket (TGT).
   * @param {ASRequest} request - Contains client ID, target TGS ID, and parameters to prevent replay attacks.
   * @returns {ASResponse} Encrypted payload containing the Session Key and the TGT.
   */
  requestTgt(request: ASRequest, callback: (error: ServiceError | null, response: ASResponse) => void): ClientUnaryCall;
  requestTgt(
    request: ASRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ASResponse) => void,
  ): ClientUnaryCall;
  requestTgt(
    request: ASRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ASResponse) => void,
  ): ClientUnaryCall;
  /**
   * @description Phase 3: TGS Exchange — Client uses the TGT to request a Service Ticket for a specific service.
   * @param {TGSRequest} request - Contains the target service ID, the TGT, and the client's authenticator.
   * @returns {TGSResponse} Encrypted payload containing the Service Ticket and the Client-Service Session Key.
   */
  requestServiceTicket(
    request: TGSRequest,
    callback: (error: ServiceError | null, response: TGSResponse) => void,
  ): ClientUnaryCall;
  requestServiceTicket(
    request: TGSRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: TGSResponse) => void,
  ): ClientUnaryCall;
  requestServiceTicket(
    request: TGSRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: TGSResponse) => void,
  ): ClientUnaryCall;
}

export const KDCServiceClient = makeGenericClientConstructor(KDCServiceService, "kdc.KDCService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): KDCServiceClient;
  service: typeof KDCServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
