// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: bank.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "minibank.bank.v1";

/** @description Transaction's status enum */
export enum TransactionStatus {
  TRANSACTION_STATUS_UNKNOWN = 0,
  TRANSACTION_STATUS_SUCCESS = 1,
  TRANSACTION_STATUS_FAILED = 2,
  UNRECOGNIZED = -1,
}

export function transactionStatusFromJSON(object: any): TransactionStatus {
  switch (object) {
    case 0:
    case "TRANSACTION_STATUS_UNKNOWN":
      return TransactionStatus.TRANSACTION_STATUS_UNKNOWN;
    case 1:
    case "TRANSACTION_STATUS_SUCCESS":
      return TransactionStatus.TRANSACTION_STATUS_SUCCESS;
    case 2:
    case "TRANSACTION_STATUS_FAILED":
      return TransactionStatus.TRANSACTION_STATUS_FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TransactionStatus.UNRECOGNIZED;
  }
}

export function transactionStatusToJSON(object: TransactionStatus): string {
  switch (object) {
    case TransactionStatus.TRANSACTION_STATUS_UNKNOWN:
      return "TRANSACTION_STATUS_UNKNOWN";
    case TransactionStatus.TRANSACTION_STATUS_SUCCESS:
      return "TRANSACTION_STATUS_SUCCESS";
    case TransactionStatus.TRANSACTION_STATUS_FAILED:
      return "TRANSACTION_STATUS_FAILED";
    case TransactionStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * @description AP_REP result payload
 * @note Use for TransferResponse.ap_rep
 */
export interface APRepResult {
  ts5Plus1: number;
  transactionId: string;
  status: TransactionStatus;
  errorCode: string;
  amount: number;
  currency: string;
  balanceAfter: number;
  completedAt: number;
}

/**
 * @description Request payload for initiating a money transfer.
 * @note Ticket_v = E_{K_v}[ client_id, K_{c,v}, pub_c, expiry ]
 * @note Auth_c = E_{K_{c,v}}[ client_id, TS5, Nonce3 ]
 * @note Cipher = E_{K_{c,v}}[ Payload + Signature ]
 * @note Payload = { from_account, to_account, amount, currency, memo }
 * @note Signature = Sign(Payload, priv_c)
 */
export interface TransferRequest {
  ticketV: Buffer;
  authenticator: Buffer;
  cipher: Buffer;
  certSn: string;
  idempotencyKey: string;
}

export interface TransferResponse {
  apRep: Buffer;
  transactionId: string;
}

/**
 * @description AP Rep Balance payload
 * @note Use for BalanceResponse.ap_rep
 * @note Unit (VND)
 * @note Echo account_id for client to confirm
 */
export interface APRepBalance {
  tsPlus1: number;
  accountId: string;
  balance: number;
  currency: string;
  lastTransactionAt: number;
}

/** @description Request payload to fetch the account balance. */
export interface BalanceRequest {
  ticketV: Buffer;
  authenticator: Buffer;
  accountId: string;
  certSn: string;
}

export interface BalanceResponse {
  apRep: Buffer;
  balance: number;
  currency: string;
}

/**
 * @description AP Rep payload for TransactionHistoryResponse.ap_rep
 * @note Put records and pagination out of ap_rep (plaintext)
 * @note Just encrypt ts_plus_1 to mutual auth
 */
export interface APRepTransactions {
  tsPlus1: number;
}

/**
 * @description History of state changes of transaction
 * @note Mapping to table TRANSACTION_DETAILS
 */
export interface TransactionStatusEvent {
  statusBefore: string;
  statusAfter: string;
  changedBy: string;
  changedAt: number;
  notes: string;
}

/**
 * @description Request payload to fetch paginated transaction history.
 * @note from_ts and to_ts are optional, which filter from/to unix timestamp
 */
export interface TransactionHistoryRequest {
  ticketV: Buffer;
  authenticator: Buffer;
  accountId: string;
  certSn: string;
  cursorLastTxId: string;
  limit: number;
  fromTs: number;
  toTs: number;
}

export interface TransactionHistoryResponse {
  apRep: Buffer;
  records: TransactionRecord[];
  nextCursor: string;
  hasMore: boolean;
}

export interface TransactionRecord {
  transactionId: string;
  fromAccount: string;
  toAccount: string;
  amount: number;
  currency: string;
  memo: string;
  createdAt: number;
  status: string;
  statusTrail: TransactionStatusTrail[];
}

export interface TransactionStatusTrail {
  statusBefore: string;
  statusAfter: string;
  changedBy: string;
  changedAt: number;
  notes: string;
}

function createBaseAPRepResult(): APRepResult {
  return {
    ts5Plus1: 0,
    transactionId: "",
    status: 0,
    errorCode: "",
    amount: 0,
    currency: "",
    balanceAfter: 0,
    completedAt: 0,
  };
}

export const APRepResult: MessageFns<APRepResult> = {
  encode(message: APRepResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ts5Plus1 !== 0) {
      writer.uint32(8).int64(message.ts5Plus1);
    }
    if (message.transactionId !== "") {
      writer.uint32(18).string(message.transactionId);
    }
    if (message.status !== 0) {
      writer.uint32(24).int32(message.status);
    }
    if (message.errorCode !== "") {
      writer.uint32(34).string(message.errorCode);
    }
    if (message.amount !== 0) {
      writer.uint32(40).int64(message.amount);
    }
    if (message.currency !== "") {
      writer.uint32(50).string(message.currency);
    }
    if (message.balanceAfter !== 0) {
      writer.uint32(56).int64(message.balanceAfter);
    }
    if (message.completedAt !== 0) {
      writer.uint32(64).int64(message.completedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): APRepResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAPRepResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ts5Plus1 = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.transactionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.errorCode = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.amount = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.balanceAfter = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.completedAt = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): APRepResult {
    return {
      ts5Plus1: isSet(object.ts5Plus1)
        ? globalThis.Number(object.ts5Plus1)
        : isSet(object.ts_5_plus_1)
        ? globalThis.Number(object.ts_5_plus_1)
        : 0,
      transactionId: isSet(object.transactionId)
        ? globalThis.String(object.transactionId)
        : isSet(object.transaction_id)
        ? globalThis.String(object.transaction_id)
        : "",
      status: isSet(object.status) ? transactionStatusFromJSON(object.status) : 0,
      errorCode: isSet(object.errorCode)
        ? globalThis.String(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.String(object.error_code)
        : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      balanceAfter: isSet(object.balanceAfter)
        ? globalThis.Number(object.balanceAfter)
        : isSet(object.balance_after)
        ? globalThis.Number(object.balance_after)
        : 0,
      completedAt: isSet(object.completedAt)
        ? globalThis.Number(object.completedAt)
        : isSet(object.completed_at)
        ? globalThis.Number(object.completed_at)
        : 0,
    };
  },

  toJSON(message: APRepResult): unknown {
    const obj: any = {};
    if (message.ts5Plus1 !== 0) {
      obj.ts5Plus1 = Math.round(message.ts5Plus1);
    }
    if (message.transactionId !== "") {
      obj.transactionId = message.transactionId;
    }
    if (message.status !== 0) {
      obj.status = transactionStatusToJSON(message.status);
    }
    if (message.errorCode !== "") {
      obj.errorCode = message.errorCode;
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.balanceAfter !== 0) {
      obj.balanceAfter = Math.round(message.balanceAfter);
    }
    if (message.completedAt !== 0) {
      obj.completedAt = Math.round(message.completedAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<APRepResult>, I>>(base?: I): APRepResult {
    return APRepResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<APRepResult>, I>>(object: I): APRepResult {
    const message = createBaseAPRepResult();
    message.ts5Plus1 = object.ts5Plus1 ?? 0;
    message.transactionId = object.transactionId ?? "";
    message.status = object.status ?? 0;
    message.errorCode = object.errorCode ?? "";
    message.amount = object.amount ?? 0;
    message.currency = object.currency ?? "";
    message.balanceAfter = object.balanceAfter ?? 0;
    message.completedAt = object.completedAt ?? 0;
    return message;
  },
};

function createBaseTransferRequest(): TransferRequest {
  return {
    ticketV: Buffer.alloc(0),
    authenticator: Buffer.alloc(0),
    cipher: Buffer.alloc(0),
    certSn: "",
    idempotencyKey: "",
  };
}

export const TransferRequest: MessageFns<TransferRequest> = {
  encode(message: TransferRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ticketV.length !== 0) {
      writer.uint32(10).bytes(message.ticketV);
    }
    if (message.authenticator.length !== 0) {
      writer.uint32(18).bytes(message.authenticator);
    }
    if (message.cipher.length !== 0) {
      writer.uint32(26).bytes(message.cipher);
    }
    if (message.certSn !== "") {
      writer.uint32(34).string(message.certSn);
    }
    if (message.idempotencyKey !== "") {
      writer.uint32(42).string(message.idempotencyKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransferRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransferRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ticketV = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.authenticator = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.cipher = Buffer.from(reader.bytes());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.certSn = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransferRequest {
    return {
      ticketV: isSet(object.ticketV)
        ? Buffer.from(bytesFromBase64(object.ticketV))
        : isSet(object.ticket_v)
        ? Buffer.from(bytesFromBase64(object.ticket_v))
        : Buffer.alloc(0),
      authenticator: isSet(object.authenticator) ? Buffer.from(bytesFromBase64(object.authenticator)) : Buffer.alloc(0),
      cipher: isSet(object.cipher) ? Buffer.from(bytesFromBase64(object.cipher)) : Buffer.alloc(0),
      certSn: isSet(object.certSn)
        ? globalThis.String(object.certSn)
        : isSet(object.cert_sn)
        ? globalThis.String(object.cert_sn)
        : "",
      idempotencyKey: isSet(object.idempotencyKey)
        ? globalThis.String(object.idempotencyKey)
        : isSet(object.idempotency_key)
        ? globalThis.String(object.idempotency_key)
        : "",
    };
  },

  toJSON(message: TransferRequest): unknown {
    const obj: any = {};
    if (message.ticketV.length !== 0) {
      obj.ticketV = base64FromBytes(message.ticketV);
    }
    if (message.authenticator.length !== 0) {
      obj.authenticator = base64FromBytes(message.authenticator);
    }
    if (message.cipher.length !== 0) {
      obj.cipher = base64FromBytes(message.cipher);
    }
    if (message.certSn !== "") {
      obj.certSn = message.certSn;
    }
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransferRequest>, I>>(base?: I): TransferRequest {
    return TransferRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransferRequest>, I>>(object: I): TransferRequest {
    const message = createBaseTransferRequest();
    message.ticketV = object.ticketV ?? Buffer.alloc(0);
    message.authenticator = object.authenticator ?? Buffer.alloc(0);
    message.cipher = object.cipher ?? Buffer.alloc(0);
    message.certSn = object.certSn ?? "";
    message.idempotencyKey = object.idempotencyKey ?? "";
    return message;
  },
};

function createBaseTransferResponse(): TransferResponse {
  return { apRep: Buffer.alloc(0), transactionId: "" };
}

export const TransferResponse: MessageFns<TransferResponse> = {
  encode(message: TransferResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.apRep.length !== 0) {
      writer.uint32(10).bytes(message.apRep);
    }
    if (message.transactionId !== "") {
      writer.uint32(18).string(message.transactionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransferResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransferResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.apRep = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.transactionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransferResponse {
    return {
      apRep: isSet(object.apRep)
        ? Buffer.from(bytesFromBase64(object.apRep))
        : isSet(object.ap_rep)
        ? Buffer.from(bytesFromBase64(object.ap_rep))
        : Buffer.alloc(0),
      transactionId: isSet(object.transactionId)
        ? globalThis.String(object.transactionId)
        : isSet(object.transaction_id)
        ? globalThis.String(object.transaction_id)
        : "",
    };
  },

  toJSON(message: TransferResponse): unknown {
    const obj: any = {};
    if (message.apRep.length !== 0) {
      obj.apRep = base64FromBytes(message.apRep);
    }
    if (message.transactionId !== "") {
      obj.transactionId = message.transactionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransferResponse>, I>>(base?: I): TransferResponse {
    return TransferResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransferResponse>, I>>(object: I): TransferResponse {
    const message = createBaseTransferResponse();
    message.apRep = object.apRep ?? Buffer.alloc(0);
    message.transactionId = object.transactionId ?? "";
    return message;
  },
};

function createBaseAPRepBalance(): APRepBalance {
  return { tsPlus1: 0, accountId: "", balance: 0, currency: "", lastTransactionAt: 0 };
}

export const APRepBalance: MessageFns<APRepBalance> = {
  encode(message: APRepBalance, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tsPlus1 !== 0) {
      writer.uint32(8).int64(message.tsPlus1);
    }
    if (message.accountId !== "") {
      writer.uint32(18).string(message.accountId);
    }
    if (message.balance !== 0) {
      writer.uint32(24).int64(message.balance);
    }
    if (message.currency !== "") {
      writer.uint32(34).string(message.currency);
    }
    if (message.lastTransactionAt !== 0) {
      writer.uint32(40).int64(message.lastTransactionAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): APRepBalance {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAPRepBalance();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tsPlus1 = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.balance = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.lastTransactionAt = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): APRepBalance {
    return {
      tsPlus1: isSet(object.tsPlus1)
        ? globalThis.Number(object.tsPlus1)
        : isSet(object.ts_plus_1)
        ? globalThis.Number(object.ts_plus_1)
        : 0,
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      balance: isSet(object.balance) ? globalThis.Number(object.balance) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      lastTransactionAt: isSet(object.lastTransactionAt)
        ? globalThis.Number(object.lastTransactionAt)
        : isSet(object.last_transaction_at)
        ? globalThis.Number(object.last_transaction_at)
        : 0,
    };
  },

  toJSON(message: APRepBalance): unknown {
    const obj: any = {};
    if (message.tsPlus1 !== 0) {
      obj.tsPlus1 = Math.round(message.tsPlus1);
    }
    if (message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.balance !== 0) {
      obj.balance = Math.round(message.balance);
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.lastTransactionAt !== 0) {
      obj.lastTransactionAt = Math.round(message.lastTransactionAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<APRepBalance>, I>>(base?: I): APRepBalance {
    return APRepBalance.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<APRepBalance>, I>>(object: I): APRepBalance {
    const message = createBaseAPRepBalance();
    message.tsPlus1 = object.tsPlus1 ?? 0;
    message.accountId = object.accountId ?? "";
    message.balance = object.balance ?? 0;
    message.currency = object.currency ?? "";
    message.lastTransactionAt = object.lastTransactionAt ?? 0;
    return message;
  },
};

function createBaseBalanceRequest(): BalanceRequest {
  return { ticketV: Buffer.alloc(0), authenticator: Buffer.alloc(0), accountId: "", certSn: "" };
}

export const BalanceRequest: MessageFns<BalanceRequest> = {
  encode(message: BalanceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ticketV.length !== 0) {
      writer.uint32(10).bytes(message.ticketV);
    }
    if (message.authenticator.length !== 0) {
      writer.uint32(18).bytes(message.authenticator);
    }
    if (message.accountId !== "") {
      writer.uint32(26).string(message.accountId);
    }
    if (message.certSn !== "") {
      writer.uint32(34).string(message.certSn);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BalanceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBalanceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ticketV = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.authenticator = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.certSn = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BalanceRequest {
    return {
      ticketV: isSet(object.ticketV)
        ? Buffer.from(bytesFromBase64(object.ticketV))
        : isSet(object.ticket_v)
        ? Buffer.from(bytesFromBase64(object.ticket_v))
        : Buffer.alloc(0),
      authenticator: isSet(object.authenticator) ? Buffer.from(bytesFromBase64(object.authenticator)) : Buffer.alloc(0),
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      certSn: isSet(object.certSn)
        ? globalThis.String(object.certSn)
        : isSet(object.cert_sn)
        ? globalThis.String(object.cert_sn)
        : "",
    };
  },

  toJSON(message: BalanceRequest): unknown {
    const obj: any = {};
    if (message.ticketV.length !== 0) {
      obj.ticketV = base64FromBytes(message.ticketV);
    }
    if (message.authenticator.length !== 0) {
      obj.authenticator = base64FromBytes(message.authenticator);
    }
    if (message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.certSn !== "") {
      obj.certSn = message.certSn;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BalanceRequest>, I>>(base?: I): BalanceRequest {
    return BalanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BalanceRequest>, I>>(object: I): BalanceRequest {
    const message = createBaseBalanceRequest();
    message.ticketV = object.ticketV ?? Buffer.alloc(0);
    message.authenticator = object.authenticator ?? Buffer.alloc(0);
    message.accountId = object.accountId ?? "";
    message.certSn = object.certSn ?? "";
    return message;
  },
};

function createBaseBalanceResponse(): BalanceResponse {
  return { apRep: Buffer.alloc(0), balance: 0, currency: "" };
}

export const BalanceResponse: MessageFns<BalanceResponse> = {
  encode(message: BalanceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.apRep.length !== 0) {
      writer.uint32(10).bytes(message.apRep);
    }
    if (message.balance !== 0) {
      writer.uint32(16).int64(message.balance);
    }
    if (message.currency !== "") {
      writer.uint32(26).string(message.currency);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BalanceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBalanceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.apRep = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.balance = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BalanceResponse {
    return {
      apRep: isSet(object.apRep)
        ? Buffer.from(bytesFromBase64(object.apRep))
        : isSet(object.ap_rep)
        ? Buffer.from(bytesFromBase64(object.ap_rep))
        : Buffer.alloc(0),
      balance: isSet(object.balance) ? globalThis.Number(object.balance) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
    };
  },

  toJSON(message: BalanceResponse): unknown {
    const obj: any = {};
    if (message.apRep.length !== 0) {
      obj.apRep = base64FromBytes(message.apRep);
    }
    if (message.balance !== 0) {
      obj.balance = Math.round(message.balance);
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BalanceResponse>, I>>(base?: I): BalanceResponse {
    return BalanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BalanceResponse>, I>>(object: I): BalanceResponse {
    const message = createBaseBalanceResponse();
    message.apRep = object.apRep ?? Buffer.alloc(0);
    message.balance = object.balance ?? 0;
    message.currency = object.currency ?? "";
    return message;
  },
};

function createBaseAPRepTransactions(): APRepTransactions {
  return { tsPlus1: 0 };
}

export const APRepTransactions: MessageFns<APRepTransactions> = {
  encode(message: APRepTransactions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tsPlus1 !== 0) {
      writer.uint32(8).int64(message.tsPlus1);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): APRepTransactions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAPRepTransactions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tsPlus1 = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): APRepTransactions {
    return {
      tsPlus1: isSet(object.tsPlus1)
        ? globalThis.Number(object.tsPlus1)
        : isSet(object.ts_plus_1)
        ? globalThis.Number(object.ts_plus_1)
        : 0,
    };
  },

  toJSON(message: APRepTransactions): unknown {
    const obj: any = {};
    if (message.tsPlus1 !== 0) {
      obj.tsPlus1 = Math.round(message.tsPlus1);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<APRepTransactions>, I>>(base?: I): APRepTransactions {
    return APRepTransactions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<APRepTransactions>, I>>(object: I): APRepTransactions {
    const message = createBaseAPRepTransactions();
    message.tsPlus1 = object.tsPlus1 ?? 0;
    return message;
  },
};

function createBaseTransactionStatusEvent(): TransactionStatusEvent {
  return { statusBefore: "", statusAfter: "", changedBy: "", changedAt: 0, notes: "" };
}

export const TransactionStatusEvent: MessageFns<TransactionStatusEvent> = {
  encode(message: TransactionStatusEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.statusBefore !== "") {
      writer.uint32(10).string(message.statusBefore);
    }
    if (message.statusAfter !== "") {
      writer.uint32(18).string(message.statusAfter);
    }
    if (message.changedBy !== "") {
      writer.uint32(26).string(message.changedBy);
    }
    if (message.changedAt !== 0) {
      writer.uint32(32).int64(message.changedAt);
    }
    if (message.notes !== "") {
      writer.uint32(42).string(message.notes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransactionStatusEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionStatusEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.statusBefore = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.statusAfter = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.changedBy = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.changedAt = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionStatusEvent {
    return {
      statusBefore: isSet(object.statusBefore)
        ? globalThis.String(object.statusBefore)
        : isSet(object.status_before)
        ? globalThis.String(object.status_before)
        : "",
      statusAfter: isSet(object.statusAfter)
        ? globalThis.String(object.statusAfter)
        : isSet(object.status_after)
        ? globalThis.String(object.status_after)
        : "",
      changedBy: isSet(object.changedBy)
        ? globalThis.String(object.changedBy)
        : isSet(object.changed_by)
        ? globalThis.String(object.changed_by)
        : "",
      changedAt: isSet(object.changedAt)
        ? globalThis.Number(object.changedAt)
        : isSet(object.changed_at)
        ? globalThis.Number(object.changed_at)
        : 0,
      notes: isSet(object.notes) ? globalThis.String(object.notes) : "",
    };
  },

  toJSON(message: TransactionStatusEvent): unknown {
    const obj: any = {};
    if (message.statusBefore !== "") {
      obj.statusBefore = message.statusBefore;
    }
    if (message.statusAfter !== "") {
      obj.statusAfter = message.statusAfter;
    }
    if (message.changedBy !== "") {
      obj.changedBy = message.changedBy;
    }
    if (message.changedAt !== 0) {
      obj.changedAt = Math.round(message.changedAt);
    }
    if (message.notes !== "") {
      obj.notes = message.notes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionStatusEvent>, I>>(base?: I): TransactionStatusEvent {
    return TransactionStatusEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionStatusEvent>, I>>(object: I): TransactionStatusEvent {
    const message = createBaseTransactionStatusEvent();
    message.statusBefore = object.statusBefore ?? "";
    message.statusAfter = object.statusAfter ?? "";
    message.changedBy = object.changedBy ?? "";
    message.changedAt = object.changedAt ?? 0;
    message.notes = object.notes ?? "";
    return message;
  },
};

function createBaseTransactionHistoryRequest(): TransactionHistoryRequest {
  return {
    ticketV: Buffer.alloc(0),
    authenticator: Buffer.alloc(0),
    accountId: "",
    certSn: "",
    cursorLastTxId: "",
    limit: 0,
    fromTs: 0,
    toTs: 0,
  };
}

export const TransactionHistoryRequest: MessageFns<TransactionHistoryRequest> = {
  encode(message: TransactionHistoryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ticketV.length !== 0) {
      writer.uint32(10).bytes(message.ticketV);
    }
    if (message.authenticator.length !== 0) {
      writer.uint32(18).bytes(message.authenticator);
    }
    if (message.accountId !== "") {
      writer.uint32(26).string(message.accountId);
    }
    if (message.certSn !== "") {
      writer.uint32(34).string(message.certSn);
    }
    if (message.cursorLastTxId !== "") {
      writer.uint32(42).string(message.cursorLastTxId);
    }
    if (message.limit !== 0) {
      writer.uint32(48).int32(message.limit);
    }
    if (message.fromTs !== 0) {
      writer.uint32(56).int64(message.fromTs);
    }
    if (message.toTs !== 0) {
      writer.uint32(64).int64(message.toTs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransactionHistoryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionHistoryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ticketV = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.authenticator = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.certSn = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.cursorLastTxId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.fromTs = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.toTs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionHistoryRequest {
    return {
      ticketV: isSet(object.ticketV)
        ? Buffer.from(bytesFromBase64(object.ticketV))
        : isSet(object.ticket_v)
        ? Buffer.from(bytesFromBase64(object.ticket_v))
        : Buffer.alloc(0),
      authenticator: isSet(object.authenticator) ? Buffer.from(bytesFromBase64(object.authenticator)) : Buffer.alloc(0),
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      certSn: isSet(object.certSn)
        ? globalThis.String(object.certSn)
        : isSet(object.cert_sn)
        ? globalThis.String(object.cert_sn)
        : "",
      cursorLastTxId: isSet(object.cursorLastTxId)
        ? globalThis.String(object.cursorLastTxId)
        : isSet(object.cursor_last_tx_id)
        ? globalThis.String(object.cursor_last_tx_id)
        : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      fromTs: isSet(object.fromTs)
        ? globalThis.Number(object.fromTs)
        : isSet(object.from_ts)
        ? globalThis.Number(object.from_ts)
        : 0,
      toTs: isSet(object.toTs)
        ? globalThis.Number(object.toTs)
        : isSet(object.to_ts)
        ? globalThis.Number(object.to_ts)
        : 0,
    };
  },

  toJSON(message: TransactionHistoryRequest): unknown {
    const obj: any = {};
    if (message.ticketV.length !== 0) {
      obj.ticketV = base64FromBytes(message.ticketV);
    }
    if (message.authenticator.length !== 0) {
      obj.authenticator = base64FromBytes(message.authenticator);
    }
    if (message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.certSn !== "") {
      obj.certSn = message.certSn;
    }
    if (message.cursorLastTxId !== "") {
      obj.cursorLastTxId = message.cursorLastTxId;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.fromTs !== 0) {
      obj.fromTs = Math.round(message.fromTs);
    }
    if (message.toTs !== 0) {
      obj.toTs = Math.round(message.toTs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionHistoryRequest>, I>>(base?: I): TransactionHistoryRequest {
    return TransactionHistoryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionHistoryRequest>, I>>(object: I): TransactionHistoryRequest {
    const message = createBaseTransactionHistoryRequest();
    message.ticketV = object.ticketV ?? Buffer.alloc(0);
    message.authenticator = object.authenticator ?? Buffer.alloc(0);
    message.accountId = object.accountId ?? "";
    message.certSn = object.certSn ?? "";
    message.cursorLastTxId = object.cursorLastTxId ?? "";
    message.limit = object.limit ?? 0;
    message.fromTs = object.fromTs ?? 0;
    message.toTs = object.toTs ?? 0;
    return message;
  },
};

function createBaseTransactionHistoryResponse(): TransactionHistoryResponse {
  return { apRep: Buffer.alloc(0), records: [], nextCursor: "", hasMore: false };
}

export const TransactionHistoryResponse: MessageFns<TransactionHistoryResponse> = {
  encode(message: TransactionHistoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.apRep.length !== 0) {
      writer.uint32(10).bytes(message.apRep);
    }
    for (const v of message.records) {
      TransactionRecord.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.nextCursor !== "") {
      writer.uint32(26).string(message.nextCursor);
    }
    if (message.hasMore !== false) {
      writer.uint32(32).bool(message.hasMore);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransactionHistoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionHistoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.apRep = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.records.push(TransactionRecord.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nextCursor = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.hasMore = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionHistoryResponse {
    return {
      apRep: isSet(object.apRep)
        ? Buffer.from(bytesFromBase64(object.apRep))
        : isSet(object.ap_rep)
        ? Buffer.from(bytesFromBase64(object.ap_rep))
        : Buffer.alloc(0),
      records: globalThis.Array.isArray(object?.records)
        ? object.records.map((e: any) => TransactionRecord.fromJSON(e))
        : [],
      nextCursor: isSet(object.nextCursor)
        ? globalThis.String(object.nextCursor)
        : isSet(object.next_cursor)
        ? globalThis.String(object.next_cursor)
        : "",
      hasMore: isSet(object.hasMore)
        ? globalThis.Boolean(object.hasMore)
        : isSet(object.has_more)
        ? globalThis.Boolean(object.has_more)
        : false,
    };
  },

  toJSON(message: TransactionHistoryResponse): unknown {
    const obj: any = {};
    if (message.apRep.length !== 0) {
      obj.apRep = base64FromBytes(message.apRep);
    }
    if (message.records?.length) {
      obj.records = message.records.map((e) => TransactionRecord.toJSON(e));
    }
    if (message.nextCursor !== "") {
      obj.nextCursor = message.nextCursor;
    }
    if (message.hasMore !== false) {
      obj.hasMore = message.hasMore;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionHistoryResponse>, I>>(base?: I): TransactionHistoryResponse {
    return TransactionHistoryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionHistoryResponse>, I>>(object: I): TransactionHistoryResponse {
    const message = createBaseTransactionHistoryResponse();
    message.apRep = object.apRep ?? Buffer.alloc(0);
    message.records = object.records?.map((e) => TransactionRecord.fromPartial(e)) || [];
    message.nextCursor = object.nextCursor ?? "";
    message.hasMore = object.hasMore ?? false;
    return message;
  },
};

function createBaseTransactionRecord(): TransactionRecord {
  return {
    transactionId: "",
    fromAccount: "",
    toAccount: "",
    amount: 0,
    currency: "",
    memo: "",
    createdAt: 0,
    status: "",
    statusTrail: [],
  };
}

export const TransactionRecord: MessageFns<TransactionRecord> = {
  encode(message: TransactionRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transactionId !== "") {
      writer.uint32(10).string(message.transactionId);
    }
    if (message.fromAccount !== "") {
      writer.uint32(18).string(message.fromAccount);
    }
    if (message.toAccount !== "") {
      writer.uint32(26).string(message.toAccount);
    }
    if (message.amount !== 0) {
      writer.uint32(32).int64(message.amount);
    }
    if (message.currency !== "") {
      writer.uint32(42).string(message.currency);
    }
    if (message.memo !== "") {
      writer.uint32(50).string(message.memo);
    }
    if (message.createdAt !== 0) {
      writer.uint32(56).int64(message.createdAt);
    }
    if (message.status !== "") {
      writer.uint32(66).string(message.status);
    }
    for (const v of message.statusTrail) {
      TransactionStatusTrail.encode(v!, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransactionRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transactionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fromAccount = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.toAccount = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.amount = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.memo = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.statusTrail.push(TransactionStatusTrail.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionRecord {
    return {
      transactionId: isSet(object.transactionId)
        ? globalThis.String(object.transactionId)
        : isSet(object.transaction_id)
        ? globalThis.String(object.transaction_id)
        : "",
      fromAccount: isSet(object.fromAccount)
        ? globalThis.String(object.fromAccount)
        : isSet(object.from_account)
        ? globalThis.String(object.from_account)
        : "",
      toAccount: isSet(object.toAccount)
        ? globalThis.String(object.toAccount)
        : isSet(object.to_account)
        ? globalThis.String(object.to_account)
        : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      memo: isSet(object.memo) ? globalThis.String(object.memo) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      statusTrail: globalThis.Array.isArray(object?.statusTrail)
        ? object.statusTrail.map((e: any) => TransactionStatusTrail.fromJSON(e))
        : globalThis.Array.isArray(object?.status_trail)
        ? object.status_trail.map((e: any) => TransactionStatusTrail.fromJSON(e))
        : [],
    };
  },

  toJSON(message: TransactionRecord): unknown {
    const obj: any = {};
    if (message.transactionId !== "") {
      obj.transactionId = message.transactionId;
    }
    if (message.fromAccount !== "") {
      obj.fromAccount = message.fromAccount;
    }
    if (message.toAccount !== "") {
      obj.toAccount = message.toAccount;
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.memo !== "") {
      obj.memo = message.memo;
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.statusTrail?.length) {
      obj.statusTrail = message.statusTrail.map((e) => TransactionStatusTrail.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionRecord>, I>>(base?: I): TransactionRecord {
    return TransactionRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionRecord>, I>>(object: I): TransactionRecord {
    const message = createBaseTransactionRecord();
    message.transactionId = object.transactionId ?? "";
    message.fromAccount = object.fromAccount ?? "";
    message.toAccount = object.toAccount ?? "";
    message.amount = object.amount ?? 0;
    message.currency = object.currency ?? "";
    message.memo = object.memo ?? "";
    message.createdAt = object.createdAt ?? 0;
    message.status = object.status ?? "";
    message.statusTrail = object.statusTrail?.map((e) => TransactionStatusTrail.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTransactionStatusTrail(): TransactionStatusTrail {
  return { statusBefore: "", statusAfter: "", changedBy: "", changedAt: 0, notes: "" };
}

export const TransactionStatusTrail: MessageFns<TransactionStatusTrail> = {
  encode(message: TransactionStatusTrail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.statusBefore !== "") {
      writer.uint32(10).string(message.statusBefore);
    }
    if (message.statusAfter !== "") {
      writer.uint32(18).string(message.statusAfter);
    }
    if (message.changedBy !== "") {
      writer.uint32(26).string(message.changedBy);
    }
    if (message.changedAt !== 0) {
      writer.uint32(32).int64(message.changedAt);
    }
    if (message.notes !== "") {
      writer.uint32(42).string(message.notes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransactionStatusTrail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionStatusTrail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.statusBefore = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.statusAfter = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.changedBy = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.changedAt = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionStatusTrail {
    return {
      statusBefore: isSet(object.statusBefore)
        ? globalThis.String(object.statusBefore)
        : isSet(object.status_before)
        ? globalThis.String(object.status_before)
        : "",
      statusAfter: isSet(object.statusAfter)
        ? globalThis.String(object.statusAfter)
        : isSet(object.status_after)
        ? globalThis.String(object.status_after)
        : "",
      changedBy: isSet(object.changedBy)
        ? globalThis.String(object.changedBy)
        : isSet(object.changed_by)
        ? globalThis.String(object.changed_by)
        : "",
      changedAt: isSet(object.changedAt)
        ? globalThis.Number(object.changedAt)
        : isSet(object.changed_at)
        ? globalThis.Number(object.changed_at)
        : 0,
      notes: isSet(object.notes) ? globalThis.String(object.notes) : "",
    };
  },

  toJSON(message: TransactionStatusTrail): unknown {
    const obj: any = {};
    if (message.statusBefore !== "") {
      obj.statusBefore = message.statusBefore;
    }
    if (message.statusAfter !== "") {
      obj.statusAfter = message.statusAfter;
    }
    if (message.changedBy !== "") {
      obj.changedBy = message.changedBy;
    }
    if (message.changedAt !== 0) {
      obj.changedAt = Math.round(message.changedAt);
    }
    if (message.notes !== "") {
      obj.notes = message.notes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionStatusTrail>, I>>(base?: I): TransactionStatusTrail {
    return TransactionStatusTrail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionStatusTrail>, I>>(object: I): TransactionStatusTrail {
    const message = createBaseTransactionStatusTrail();
    message.statusBefore = object.statusBefore ?? "";
    message.statusAfter = object.statusAfter ?? "";
    message.changedBy = object.changedBy ?? "";
    message.changedAt = object.changedAt ?? 0;
    message.notes = object.notes ?? "";
    return message;
  },
};

export type BankServiceService = typeof BankServiceService;
export const BankServiceService = {
  transferMoney: {
    path: "/minibank.bank.v1.BankService/TransferMoney" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: TransferRequest): Buffer => Buffer.from(TransferRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): TransferRequest => TransferRequest.decode(value),
    responseSerialize: (value: TransferResponse): Buffer => Buffer.from(TransferResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): TransferResponse => TransferResponse.decode(value),
  },
  getBalance: {
    path: "/minibank.bank.v1.BankService/GetBalance" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: BalanceRequest): Buffer => Buffer.from(BalanceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): BalanceRequest => BalanceRequest.decode(value),
    responseSerialize: (value: BalanceResponse): Buffer => Buffer.from(BalanceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BalanceResponse => BalanceResponse.decode(value),
  },
  getTransactions: {
    path: "/minibank.bank.v1.BankService/GetTransactions" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: TransactionHistoryRequest): Buffer =>
      Buffer.from(TransactionHistoryRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): TransactionHistoryRequest => TransactionHistoryRequest.decode(value),
    responseSerialize: (value: TransactionHistoryResponse): Buffer =>
      Buffer.from(TransactionHistoryResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): TransactionHistoryResponse => TransactionHistoryResponse.decode(value),
  },
} as const;

export interface BankServiceServer extends UntypedServiceImplementation {
  transferMoney: handleUnaryCall<TransferRequest, TransferResponse>;
  getBalance: handleUnaryCall<BalanceRequest, BalanceResponse>;
  getTransactions: handleUnaryCall<TransactionHistoryRequest, TransactionHistoryResponse>;
}

export interface BankServiceClient extends Client {
  transferMoney(
    request: TransferRequest,
    callback: (error: ServiceError | null, response: TransferResponse) => void,
  ): ClientUnaryCall;
  transferMoney(
    request: TransferRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: TransferResponse) => void,
  ): ClientUnaryCall;
  transferMoney(
    request: TransferRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: TransferResponse) => void,
  ): ClientUnaryCall;
  getBalance(
    request: BalanceRequest,
    callback: (error: ServiceError | null, response: BalanceResponse) => void,
  ): ClientUnaryCall;
  getBalance(
    request: BalanceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: BalanceResponse) => void,
  ): ClientUnaryCall;
  getBalance(
    request: BalanceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: BalanceResponse) => void,
  ): ClientUnaryCall;
  getTransactions(
    request: TransactionHistoryRequest,
    callback: (error: ServiceError | null, response: TransactionHistoryResponse) => void,
  ): ClientUnaryCall;
  getTransactions(
    request: TransactionHistoryRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: TransactionHistoryResponse) => void,
  ): ClientUnaryCall;
  getTransactions(
    request: TransactionHistoryRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: TransactionHistoryResponse) => void,
  ): ClientUnaryCall;
}

export const BankServiceClient = makeGenericClientConstructor(
  BankServiceService,
  "minibank.bank.v1.BankService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): BankServiceClient;
  service: typeof BankServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
