// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: bank.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "bank";

export enum AccountStatus {
  ACCOUNT_STATUS_UNKNOWN = 0,
  ACCOUNT_STATUS_ACTIVE = 1,
  ACCOUNT_STATUS_LOCKED = 2,
  ACCOUNT_STATUS_FROZEN = 3,
  UNRECOGNIZED = -1,
}

export function accountStatusFromJSON(object: any): AccountStatus {
  switch (object) {
    case 0:
    case "ACCOUNT_STATUS_UNKNOWN":
      return AccountStatus.ACCOUNT_STATUS_UNKNOWN;
    case 1:
    case "ACCOUNT_STATUS_ACTIVE":
      return AccountStatus.ACCOUNT_STATUS_ACTIVE;
    case 2:
    case "ACCOUNT_STATUS_LOCKED":
      return AccountStatus.ACCOUNT_STATUS_LOCKED;
    case 3:
    case "ACCOUNT_STATUS_FROZEN":
      return AccountStatus.ACCOUNT_STATUS_FROZEN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AccountStatus.UNRECOGNIZED;
  }
}

export function accountStatusToJSON(object: AccountStatus): string {
  switch (object) {
    case AccountStatus.ACCOUNT_STATUS_UNKNOWN:
      return "ACCOUNT_STATUS_UNKNOWN";
    case AccountStatus.ACCOUNT_STATUS_ACTIVE:
      return "ACCOUNT_STATUS_ACTIVE";
    case AccountStatus.ACCOUNT_STATUS_LOCKED:
      return "ACCOUNT_STATUS_LOCKED";
    case AccountStatus.ACCOUNT_STATUS_FROZEN:
      return "ACCOUNT_STATUS_FROZEN";
    case AccountStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TransactionStatus {
  TRANSACTION_STATUS_UNKNOWN = 0,
  TRANSACTION_STATUS_PENDING = 1,
  TRANSACTION_STATUS_COMPLETED = 2,
  TRANSACTION_STATUS_FAILED = 3,
  UNRECOGNIZED = -1,
}

export function transactionStatusFromJSON(object: any): TransactionStatus {
  switch (object) {
    case 0:
    case "TRANSACTION_STATUS_UNKNOWN":
      return TransactionStatus.TRANSACTION_STATUS_UNKNOWN;
    case 1:
    case "TRANSACTION_STATUS_PENDING":
      return TransactionStatus.TRANSACTION_STATUS_PENDING;
    case 2:
    case "TRANSACTION_STATUS_COMPLETED":
      return TransactionStatus.TRANSACTION_STATUS_COMPLETED;
    case 3:
    case "TRANSACTION_STATUS_FAILED":
      return TransactionStatus.TRANSACTION_STATUS_FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TransactionStatus.UNRECOGNIZED;
  }
}

export function transactionStatusToJSON(object: TransactionStatus): string {
  switch (object) {
    case TransactionStatus.TRANSACTION_STATUS_UNKNOWN:
      return "TRANSACTION_STATUS_UNKNOWN";
    case TransactionStatus.TRANSACTION_STATUS_PENDING:
      return "TRANSACTION_STATUS_PENDING";
    case TransactionStatus.TRANSACTION_STATUS_COMPLETED:
      return "TRANSACTION_STATUS_COMPLETED";
    case TransactionStatus.TRANSACTION_STATUS_FAILED:
      return "TRANSACTION_STATUS_FAILED";
    case TransactionStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CreateUserRequest {
  /** owner_id của cert */
  userId: string;
  subjectEmail: string;
  fullName: string;
}

export interface CreateUserResponse {
  userId: string;
  status: string;
  createdAtUnix: number;
}

export interface TransferRequest {
  ticketV: Buffer;
  authenticator: Buffer;
  cipherPayload: Buffer;
  iv: Buffer;
}

export interface TransferResponse {
  apRep: Buffer;
  transactionId: string;
}

export interface BalanceRequest {
  ticketV: Buffer;
  authenticator: Buffer;
  accountId: string;
}

export interface BalanceResponse {
  apRep: Buffer;
  accountId: string;
  accountNumber: string;
  balance: number;
  currency: string;
  status: AccountStatus;
}

export interface HistoryRequest {
  ticketV: Buffer;
  authenticator: Buffer;
  accountId: string;
  limit: number;
  offset: number;
}

export interface HistoryResponse {
  apRep: Buffer;
  transactions: TransactionRecord[];
  total: number;
  limit: number;
  offset: number;
}

export interface ListAuditEventsRequest {
  action: string;
  userId: string;
  certSerial: string;
  requestId: string;
  fromUnix: number;
  toUnix: number;
  limit: number;
  offset: number;
}

export interface BankAuditRecord {
  id: string;
  action: string;
  userId: string;
  accountId: string;
  transactionId: string;
  certSerial: string;
  requestId: string;
  reason: string;
  metadataJson: string;
  createdAtUnix: number;
}

export interface ListAuditEventsResponse {
  events: BankAuditRecord[];
  total: number;
  limit: number;
  offset: number;
}

export interface TransactionRecord {
  transactionId: string;
  fromAccountNumber: string;
  toAccountNumber: string;
  amount: number;
  currency: string;
  status: TransactionStatus;
  description: string;
  scope: string;
  createdAtUnix: number;
  completedAtUnix: number;
}

function createBaseCreateUserRequest(): CreateUserRequest {
  return { userId: "", subjectEmail: "", fullName: "" };
}

export const CreateUserRequest: MessageFns<CreateUserRequest> = {
  encode(message: CreateUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.subjectEmail !== "") {
      writer.uint32(18).string(message.subjectEmail);
    }
    if (message.fullName !== "") {
      writer.uint32(26).string(message.fullName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subjectEmail = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.fullName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateUserRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      subjectEmail: isSet(object.subjectEmail)
        ? globalThis.String(object.subjectEmail)
        : isSet(object.subject_email)
        ? globalThis.String(object.subject_email)
        : "",
      fullName: isSet(object.fullName)
        ? globalThis.String(object.fullName)
        : isSet(object.full_name)
        ? globalThis.String(object.full_name)
        : "",
    };
  },

  toJSON(message: CreateUserRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.subjectEmail !== "") {
      obj.subjectEmail = message.subjectEmail;
    }
    if (message.fullName !== "") {
      obj.fullName = message.fullName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateUserRequest>, I>>(base?: I): CreateUserRequest {
    return CreateUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateUserRequest>, I>>(object: I): CreateUserRequest {
    const message = createBaseCreateUserRequest();
    message.userId = object.userId ?? "";
    message.subjectEmail = object.subjectEmail ?? "";
    message.fullName = object.fullName ?? "";
    return message;
  },
};

function createBaseCreateUserResponse(): CreateUserResponse {
  return { userId: "", status: "", createdAtUnix: 0 };
}

export const CreateUserResponse: MessageFns<CreateUserResponse> = {
  encode(message: CreateUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.createdAtUnix !== 0) {
      writer.uint32(24).int64(message.createdAtUnix);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.createdAtUnix = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateUserResponse {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      createdAtUnix: isSet(object.createdAtUnix)
        ? globalThis.Number(object.createdAtUnix)
        : isSet(object.created_at_unix)
        ? globalThis.Number(object.created_at_unix)
        : 0,
    };
  },

  toJSON(message: CreateUserResponse): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.createdAtUnix !== 0) {
      obj.createdAtUnix = Math.round(message.createdAtUnix);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateUserResponse>, I>>(base?: I): CreateUserResponse {
    return CreateUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateUserResponse>, I>>(object: I): CreateUserResponse {
    const message = createBaseCreateUserResponse();
    message.userId = object.userId ?? "";
    message.status = object.status ?? "";
    message.createdAtUnix = object.createdAtUnix ?? 0;
    return message;
  },
};

function createBaseTransferRequest(): TransferRequest {
  return {
    ticketV: Buffer.alloc(0),
    authenticator: Buffer.alloc(0),
    cipherPayload: Buffer.alloc(0),
    iv: Buffer.alloc(0),
  };
}

export const TransferRequest: MessageFns<TransferRequest> = {
  encode(message: TransferRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ticketV.length !== 0) {
      writer.uint32(10).bytes(message.ticketV);
    }
    if (message.authenticator.length !== 0) {
      writer.uint32(18).bytes(message.authenticator);
    }
    if (message.cipherPayload.length !== 0) {
      writer.uint32(26).bytes(message.cipherPayload);
    }
    if (message.iv.length !== 0) {
      writer.uint32(34).bytes(message.iv);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransferRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransferRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ticketV = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.authenticator = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.cipherPayload = Buffer.from(reader.bytes());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.iv = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransferRequest {
    return {
      ticketV: isSet(object.ticketV)
        ? Buffer.from(bytesFromBase64(object.ticketV))
        : isSet(object.ticket_v)
        ? Buffer.from(bytesFromBase64(object.ticket_v))
        : Buffer.alloc(0),
      authenticator: isSet(object.authenticator) ? Buffer.from(bytesFromBase64(object.authenticator)) : Buffer.alloc(0),
      cipherPayload: isSet(object.cipherPayload)
        ? Buffer.from(bytesFromBase64(object.cipherPayload))
        : isSet(object.cipher_payload)
        ? Buffer.from(bytesFromBase64(object.cipher_payload))
        : Buffer.alloc(0),
      iv: isSet(object.iv) ? Buffer.from(bytesFromBase64(object.iv)) : Buffer.alloc(0),
    };
  },

  toJSON(message: TransferRequest): unknown {
    const obj: any = {};
    if (message.ticketV.length !== 0) {
      obj.ticketV = base64FromBytes(message.ticketV);
    }
    if (message.authenticator.length !== 0) {
      obj.authenticator = base64FromBytes(message.authenticator);
    }
    if (message.cipherPayload.length !== 0) {
      obj.cipherPayload = base64FromBytes(message.cipherPayload);
    }
    if (message.iv.length !== 0) {
      obj.iv = base64FromBytes(message.iv);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransferRequest>, I>>(base?: I): TransferRequest {
    return TransferRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransferRequest>, I>>(object: I): TransferRequest {
    const message = createBaseTransferRequest();
    message.ticketV = object.ticketV ?? Buffer.alloc(0);
    message.authenticator = object.authenticator ?? Buffer.alloc(0);
    message.cipherPayload = object.cipherPayload ?? Buffer.alloc(0);
    message.iv = object.iv ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseTransferResponse(): TransferResponse {
  return { apRep: Buffer.alloc(0), transactionId: "" };
}

export const TransferResponse: MessageFns<TransferResponse> = {
  encode(message: TransferResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.apRep.length !== 0) {
      writer.uint32(10).bytes(message.apRep);
    }
    if (message.transactionId !== "") {
      writer.uint32(18).string(message.transactionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransferResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransferResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.apRep = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.transactionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransferResponse {
    return {
      apRep: isSet(object.apRep)
        ? Buffer.from(bytesFromBase64(object.apRep))
        : isSet(object.ap_rep)
        ? Buffer.from(bytesFromBase64(object.ap_rep))
        : Buffer.alloc(0),
      transactionId: isSet(object.transactionId)
        ? globalThis.String(object.transactionId)
        : isSet(object.transaction_id)
        ? globalThis.String(object.transaction_id)
        : "",
    };
  },

  toJSON(message: TransferResponse): unknown {
    const obj: any = {};
    if (message.apRep.length !== 0) {
      obj.apRep = base64FromBytes(message.apRep);
    }
    if (message.transactionId !== "") {
      obj.transactionId = message.transactionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransferResponse>, I>>(base?: I): TransferResponse {
    return TransferResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransferResponse>, I>>(object: I): TransferResponse {
    const message = createBaseTransferResponse();
    message.apRep = object.apRep ?? Buffer.alloc(0);
    message.transactionId = object.transactionId ?? "";
    return message;
  },
};

function createBaseBalanceRequest(): BalanceRequest {
  return { ticketV: Buffer.alloc(0), authenticator: Buffer.alloc(0), accountId: "" };
}

export const BalanceRequest: MessageFns<BalanceRequest> = {
  encode(message: BalanceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ticketV.length !== 0) {
      writer.uint32(10).bytes(message.ticketV);
    }
    if (message.authenticator.length !== 0) {
      writer.uint32(18).bytes(message.authenticator);
    }
    if (message.accountId !== "") {
      writer.uint32(26).string(message.accountId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BalanceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBalanceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ticketV = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.authenticator = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BalanceRequest {
    return {
      ticketV: isSet(object.ticketV)
        ? Buffer.from(bytesFromBase64(object.ticketV))
        : isSet(object.ticket_v)
        ? Buffer.from(bytesFromBase64(object.ticket_v))
        : Buffer.alloc(0),
      authenticator: isSet(object.authenticator) ? Buffer.from(bytesFromBase64(object.authenticator)) : Buffer.alloc(0),
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
    };
  },

  toJSON(message: BalanceRequest): unknown {
    const obj: any = {};
    if (message.ticketV.length !== 0) {
      obj.ticketV = base64FromBytes(message.ticketV);
    }
    if (message.authenticator.length !== 0) {
      obj.authenticator = base64FromBytes(message.authenticator);
    }
    if (message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BalanceRequest>, I>>(base?: I): BalanceRequest {
    return BalanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BalanceRequest>, I>>(object: I): BalanceRequest {
    const message = createBaseBalanceRequest();
    message.ticketV = object.ticketV ?? Buffer.alloc(0);
    message.authenticator = object.authenticator ?? Buffer.alloc(0);
    message.accountId = object.accountId ?? "";
    return message;
  },
};

function createBaseBalanceResponse(): BalanceResponse {
  return { apRep: Buffer.alloc(0), accountId: "", accountNumber: "", balance: 0, currency: "", status: 0 };
}

export const BalanceResponse: MessageFns<BalanceResponse> = {
  encode(message: BalanceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.apRep.length !== 0) {
      writer.uint32(10).bytes(message.apRep);
    }
    if (message.accountId !== "") {
      writer.uint32(18).string(message.accountId);
    }
    if (message.accountNumber !== "") {
      writer.uint32(26).string(message.accountNumber);
    }
    if (message.balance !== 0) {
      writer.uint32(32).int64(message.balance);
    }
    if (message.currency !== "") {
      writer.uint32(42).string(message.currency);
    }
    if (message.status !== 0) {
      writer.uint32(48).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BalanceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBalanceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.apRep = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.accountNumber = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.balance = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BalanceResponse {
    return {
      apRep: isSet(object.apRep)
        ? Buffer.from(bytesFromBase64(object.apRep))
        : isSet(object.ap_rep)
        ? Buffer.from(bytesFromBase64(object.ap_rep))
        : Buffer.alloc(0),
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      accountNumber: isSet(object.accountNumber)
        ? globalThis.String(object.accountNumber)
        : isSet(object.account_number)
        ? globalThis.String(object.account_number)
        : "",
      balance: isSet(object.balance) ? globalThis.Number(object.balance) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      status: isSet(object.status) ? accountStatusFromJSON(object.status) : 0,
    };
  },

  toJSON(message: BalanceResponse): unknown {
    const obj: any = {};
    if (message.apRep.length !== 0) {
      obj.apRep = base64FromBytes(message.apRep);
    }
    if (message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.accountNumber !== "") {
      obj.accountNumber = message.accountNumber;
    }
    if (message.balance !== 0) {
      obj.balance = Math.round(message.balance);
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.status !== 0) {
      obj.status = accountStatusToJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BalanceResponse>, I>>(base?: I): BalanceResponse {
    return BalanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BalanceResponse>, I>>(object: I): BalanceResponse {
    const message = createBaseBalanceResponse();
    message.apRep = object.apRep ?? Buffer.alloc(0);
    message.accountId = object.accountId ?? "";
    message.accountNumber = object.accountNumber ?? "";
    message.balance = object.balance ?? 0;
    message.currency = object.currency ?? "";
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseHistoryRequest(): HistoryRequest {
  return { ticketV: Buffer.alloc(0), authenticator: Buffer.alloc(0), accountId: "", limit: 0, offset: 0 };
}

export const HistoryRequest: MessageFns<HistoryRequest> = {
  encode(message: HistoryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ticketV.length !== 0) {
      writer.uint32(10).bytes(message.ticketV);
    }
    if (message.authenticator.length !== 0) {
      writer.uint32(18).bytes(message.authenticator);
    }
    if (message.accountId !== "") {
      writer.uint32(26).string(message.accountId);
    }
    if (message.limit !== 0) {
      writer.uint32(32).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(40).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HistoryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHistoryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ticketV = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.authenticator = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HistoryRequest {
    return {
      ticketV: isSet(object.ticketV)
        ? Buffer.from(bytesFromBase64(object.ticketV))
        : isSet(object.ticket_v)
        ? Buffer.from(bytesFromBase64(object.ticket_v))
        : Buffer.alloc(0),
      authenticator: isSet(object.authenticator) ? Buffer.from(bytesFromBase64(object.authenticator)) : Buffer.alloc(0),
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
    };
  },

  toJSON(message: HistoryRequest): unknown {
    const obj: any = {};
    if (message.ticketV.length !== 0) {
      obj.ticketV = base64FromBytes(message.ticketV);
    }
    if (message.authenticator.length !== 0) {
      obj.authenticator = base64FromBytes(message.authenticator);
    }
    if (message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HistoryRequest>, I>>(base?: I): HistoryRequest {
    return HistoryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HistoryRequest>, I>>(object: I): HistoryRequest {
    const message = createBaseHistoryRequest();
    message.ticketV = object.ticketV ?? Buffer.alloc(0);
    message.authenticator = object.authenticator ?? Buffer.alloc(0);
    message.accountId = object.accountId ?? "";
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    return message;
  },
};

function createBaseHistoryResponse(): HistoryResponse {
  return { apRep: Buffer.alloc(0), transactions: [], total: 0, limit: 0, offset: 0 };
}

export const HistoryResponse: MessageFns<HistoryResponse> = {
  encode(message: HistoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.apRep.length !== 0) {
      writer.uint32(10).bytes(message.apRep);
    }
    for (const v of message.transactions) {
      TransactionRecord.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(24).int32(message.total);
    }
    if (message.limit !== 0) {
      writer.uint32(32).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(40).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HistoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHistoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.apRep = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.transactions.push(TransactionRecord.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HistoryResponse {
    return {
      apRep: isSet(object.apRep)
        ? Buffer.from(bytesFromBase64(object.apRep))
        : isSet(object.ap_rep)
        ? Buffer.from(bytesFromBase64(object.ap_rep))
        : Buffer.alloc(0),
      transactions: globalThis.Array.isArray(object?.transactions)
        ? object.transactions.map((e: any) => TransactionRecord.fromJSON(e))
        : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
    };
  },

  toJSON(message: HistoryResponse): unknown {
    const obj: any = {};
    if (message.apRep.length !== 0) {
      obj.apRep = base64FromBytes(message.apRep);
    }
    if (message.transactions?.length) {
      obj.transactions = message.transactions.map((e) => TransactionRecord.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HistoryResponse>, I>>(base?: I): HistoryResponse {
    return HistoryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HistoryResponse>, I>>(object: I): HistoryResponse {
    const message = createBaseHistoryResponse();
    message.apRep = object.apRep ?? Buffer.alloc(0);
    message.transactions = object.transactions?.map((e) => TransactionRecord.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    return message;
  },
};

function createBaseListAuditEventsRequest(): ListAuditEventsRequest {
  return { action: "", userId: "", certSerial: "", requestId: "", fromUnix: 0, toUnix: 0, limit: 0, offset: 0 };
}

export const ListAuditEventsRequest: MessageFns<ListAuditEventsRequest> = {
  encode(message: ListAuditEventsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.action !== "") {
      writer.uint32(10).string(message.action);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.certSerial !== "") {
      writer.uint32(26).string(message.certSerial);
    }
    if (message.requestId !== "") {
      writer.uint32(34).string(message.requestId);
    }
    if (message.fromUnix !== 0) {
      writer.uint32(40).int64(message.fromUnix);
    }
    if (message.toUnix !== 0) {
      writer.uint32(48).int64(message.toUnix);
    }
    if (message.limit !== 0) {
      writer.uint32(56).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(64).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAuditEventsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAuditEventsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.certSerial = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.fromUnix = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.toUnix = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAuditEventsRequest {
    return {
      action: isSet(object.action) ? globalThis.String(object.action) : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      certSerial: isSet(object.certSerial)
        ? globalThis.String(object.certSerial)
        : isSet(object.cert_serial)
        ? globalThis.String(object.cert_serial)
        : "",
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      fromUnix: isSet(object.fromUnix)
        ? globalThis.Number(object.fromUnix)
        : isSet(object.from_unix)
        ? globalThis.Number(object.from_unix)
        : 0,
      toUnix: isSet(object.toUnix)
        ? globalThis.Number(object.toUnix)
        : isSet(object.to_unix)
        ? globalThis.Number(object.to_unix)
        : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
    };
  },

  toJSON(message: ListAuditEventsRequest): unknown {
    const obj: any = {};
    if (message.action !== "") {
      obj.action = message.action;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.certSerial !== "") {
      obj.certSerial = message.certSerial;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.fromUnix !== 0) {
      obj.fromUnix = Math.round(message.fromUnix);
    }
    if (message.toUnix !== 0) {
      obj.toUnix = Math.round(message.toUnix);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAuditEventsRequest>, I>>(base?: I): ListAuditEventsRequest {
    return ListAuditEventsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAuditEventsRequest>, I>>(object: I): ListAuditEventsRequest {
    const message = createBaseListAuditEventsRequest();
    message.action = object.action ?? "";
    message.userId = object.userId ?? "";
    message.certSerial = object.certSerial ?? "";
    message.requestId = object.requestId ?? "";
    message.fromUnix = object.fromUnix ?? 0;
    message.toUnix = object.toUnix ?? 0;
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    return message;
  },
};

function createBaseBankAuditRecord(): BankAuditRecord {
  return {
    id: "",
    action: "",
    userId: "",
    accountId: "",
    transactionId: "",
    certSerial: "",
    requestId: "",
    reason: "",
    metadataJson: "",
    createdAtUnix: 0,
  };
}

export const BankAuditRecord: MessageFns<BankAuditRecord> = {
  encode(message: BankAuditRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.action !== "") {
      writer.uint32(18).string(message.action);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.accountId !== "") {
      writer.uint32(34).string(message.accountId);
    }
    if (message.transactionId !== "") {
      writer.uint32(42).string(message.transactionId);
    }
    if (message.certSerial !== "") {
      writer.uint32(50).string(message.certSerial);
    }
    if (message.requestId !== "") {
      writer.uint32(58).string(message.requestId);
    }
    if (message.reason !== "") {
      writer.uint32(66).string(message.reason);
    }
    if (message.metadataJson !== "") {
      writer.uint32(74).string(message.metadataJson);
    }
    if (message.createdAtUnix !== 0) {
      writer.uint32(80).int64(message.createdAtUnix);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BankAuditRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBankAuditRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.transactionId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.certSerial = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.metadataJson = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.createdAtUnix = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BankAuditRecord {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      action: isSet(object.action) ? globalThis.String(object.action) : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      transactionId: isSet(object.transactionId)
        ? globalThis.String(object.transactionId)
        : isSet(object.transaction_id)
        ? globalThis.String(object.transaction_id)
        : "",
      certSerial: isSet(object.certSerial)
        ? globalThis.String(object.certSerial)
        : isSet(object.cert_serial)
        ? globalThis.String(object.cert_serial)
        : "",
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      metadataJson: isSet(object.metadataJson)
        ? globalThis.String(object.metadataJson)
        : isSet(object.metadata_json)
        ? globalThis.String(object.metadata_json)
        : "",
      createdAtUnix: isSet(object.createdAtUnix)
        ? globalThis.Number(object.createdAtUnix)
        : isSet(object.created_at_unix)
        ? globalThis.Number(object.created_at_unix)
        : 0,
    };
  },

  toJSON(message: BankAuditRecord): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.action !== "") {
      obj.action = message.action;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.transactionId !== "") {
      obj.transactionId = message.transactionId;
    }
    if (message.certSerial !== "") {
      obj.certSerial = message.certSerial;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.metadataJson !== "") {
      obj.metadataJson = message.metadataJson;
    }
    if (message.createdAtUnix !== 0) {
      obj.createdAtUnix = Math.round(message.createdAtUnix);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BankAuditRecord>, I>>(base?: I): BankAuditRecord {
    return BankAuditRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BankAuditRecord>, I>>(object: I): BankAuditRecord {
    const message = createBaseBankAuditRecord();
    message.id = object.id ?? "";
    message.action = object.action ?? "";
    message.userId = object.userId ?? "";
    message.accountId = object.accountId ?? "";
    message.transactionId = object.transactionId ?? "";
    message.certSerial = object.certSerial ?? "";
    message.requestId = object.requestId ?? "";
    message.reason = object.reason ?? "";
    message.metadataJson = object.metadataJson ?? "";
    message.createdAtUnix = object.createdAtUnix ?? 0;
    return message;
  },
};

function createBaseListAuditEventsResponse(): ListAuditEventsResponse {
  return { events: [], total: 0, limit: 0, offset: 0 };
}

export const ListAuditEventsResponse: MessageFns<ListAuditEventsResponse> = {
  encode(message: ListAuditEventsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.events) {
      BankAuditRecord.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(32).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAuditEventsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAuditEventsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.events.push(BankAuditRecord.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAuditEventsResponse {
    return {
      events: globalThis.Array.isArray(object?.events)
        ? object.events.map((e: any) => BankAuditRecord.fromJSON(e))
        : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
    };
  },

  toJSON(message: ListAuditEventsResponse): unknown {
    const obj: any = {};
    if (message.events?.length) {
      obj.events = message.events.map((e) => BankAuditRecord.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAuditEventsResponse>, I>>(base?: I): ListAuditEventsResponse {
    return ListAuditEventsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAuditEventsResponse>, I>>(object: I): ListAuditEventsResponse {
    const message = createBaseListAuditEventsResponse();
    message.events = object.events?.map((e) => BankAuditRecord.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    return message;
  },
};

function createBaseTransactionRecord(): TransactionRecord {
  return {
    transactionId: "",
    fromAccountNumber: "",
    toAccountNumber: "",
    amount: 0,
    currency: "",
    status: 0,
    description: "",
    scope: "",
    createdAtUnix: 0,
    completedAtUnix: 0,
  };
}

export const TransactionRecord: MessageFns<TransactionRecord> = {
  encode(message: TransactionRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transactionId !== "") {
      writer.uint32(10).string(message.transactionId);
    }
    if (message.fromAccountNumber !== "") {
      writer.uint32(18).string(message.fromAccountNumber);
    }
    if (message.toAccountNumber !== "") {
      writer.uint32(26).string(message.toAccountNumber);
    }
    if (message.amount !== 0) {
      writer.uint32(32).int64(message.amount);
    }
    if (message.currency !== "") {
      writer.uint32(42).string(message.currency);
    }
    if (message.status !== 0) {
      writer.uint32(48).int32(message.status);
    }
    if (message.description !== "") {
      writer.uint32(58).string(message.description);
    }
    if (message.scope !== "") {
      writer.uint32(66).string(message.scope);
    }
    if (message.createdAtUnix !== 0) {
      writer.uint32(72).int64(message.createdAtUnix);
    }
    if (message.completedAtUnix !== 0) {
      writer.uint32(80).int64(message.completedAtUnix);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransactionRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transactionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fromAccountNumber = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.toAccountNumber = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.amount = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.scope = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.createdAtUnix = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.completedAtUnix = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionRecord {
    return {
      transactionId: isSet(object.transactionId)
        ? globalThis.String(object.transactionId)
        : isSet(object.transaction_id)
        ? globalThis.String(object.transaction_id)
        : "",
      fromAccountNumber: isSet(object.fromAccountNumber)
        ? globalThis.String(object.fromAccountNumber)
        : isSet(object.from_account_number)
        ? globalThis.String(object.from_account_number)
        : "",
      toAccountNumber: isSet(object.toAccountNumber)
        ? globalThis.String(object.toAccountNumber)
        : isSet(object.to_account_number)
        ? globalThis.String(object.to_account_number)
        : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      status: isSet(object.status) ? transactionStatusFromJSON(object.status) : 0,
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      scope: isSet(object.scope) ? globalThis.String(object.scope) : "",
      createdAtUnix: isSet(object.createdAtUnix)
        ? globalThis.Number(object.createdAtUnix)
        : isSet(object.created_at_unix)
        ? globalThis.Number(object.created_at_unix)
        : 0,
      completedAtUnix: isSet(object.completedAtUnix)
        ? globalThis.Number(object.completedAtUnix)
        : isSet(object.completed_at_unix)
        ? globalThis.Number(object.completed_at_unix)
        : 0,
    };
  },

  toJSON(message: TransactionRecord): unknown {
    const obj: any = {};
    if (message.transactionId !== "") {
      obj.transactionId = message.transactionId;
    }
    if (message.fromAccountNumber !== "") {
      obj.fromAccountNumber = message.fromAccountNumber;
    }
    if (message.toAccountNumber !== "") {
      obj.toAccountNumber = message.toAccountNumber;
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.status !== 0) {
      obj.status = transactionStatusToJSON(message.status);
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.scope !== "") {
      obj.scope = message.scope;
    }
    if (message.createdAtUnix !== 0) {
      obj.createdAtUnix = Math.round(message.createdAtUnix);
    }
    if (message.completedAtUnix !== 0) {
      obj.completedAtUnix = Math.round(message.completedAtUnix);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionRecord>, I>>(base?: I): TransactionRecord {
    return TransactionRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionRecord>, I>>(object: I): TransactionRecord {
    const message = createBaseTransactionRecord();
    message.transactionId = object.transactionId ?? "";
    message.fromAccountNumber = object.fromAccountNumber ?? "";
    message.toAccountNumber = object.toAccountNumber ?? "";
    message.amount = object.amount ?? 0;
    message.currency = object.currency ?? "";
    message.status = object.status ?? 0;
    message.description = object.description ?? "";
    message.scope = object.scope ?? "";
    message.createdAtUnix = object.createdAtUnix ?? 0;
    message.completedAtUnix = object.completedAtUnix ?? 0;
    return message;
  },
};

/**
 * BankService owns users, accounts, AP exchange validation, transfers,
 * idempotency, audit events, and the hash-chain ledger.
 */
export type BankServiceService = typeof BankServiceService;
export const BankServiceService = {
  createUser: {
    path: "/bank.BankService/CreateUser" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateUserRequest): Buffer => Buffer.from(CreateUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateUserRequest => CreateUserRequest.decode(value),
    responseSerialize: (value: CreateUserResponse): Buffer => Buffer.from(CreateUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateUserResponse => CreateUserResponse.decode(value),
  },
  transferMoney: {
    path: "/bank.BankService/TransferMoney" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: TransferRequest): Buffer => Buffer.from(TransferRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): TransferRequest => TransferRequest.decode(value),
    responseSerialize: (value: TransferResponse): Buffer => Buffer.from(TransferResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): TransferResponse => TransferResponse.decode(value),
  },
  getBalance: {
    path: "/bank.BankService/GetBalance" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: BalanceRequest): Buffer => Buffer.from(BalanceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): BalanceRequest => BalanceRequest.decode(value),
    responseSerialize: (value: BalanceResponse): Buffer => Buffer.from(BalanceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BalanceResponse => BalanceResponse.decode(value),
  },
  getHistory: {
    path: "/bank.BankService/GetHistory" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HistoryRequest): Buffer => Buffer.from(HistoryRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HistoryRequest => HistoryRequest.decode(value),
    responseSerialize: (value: HistoryResponse): Buffer => Buffer.from(HistoryResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HistoryResponse => HistoryResponse.decode(value),
  },
  /**
   * Admin dashboard read-only audit log listing. Trust boundary: this RPC is
   * only reachable on the internal TLS gRPC network; admin authn/authz happens
   * at the API Gateway before it forwards the call.
   */
  listAuditEvents: {
    path: "/bank.BankService/ListAuditEvents" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListAuditEventsRequest): Buffer =>
      Buffer.from(ListAuditEventsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListAuditEventsRequest => ListAuditEventsRequest.decode(value),
    responseSerialize: (value: ListAuditEventsResponse): Buffer =>
      Buffer.from(ListAuditEventsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListAuditEventsResponse => ListAuditEventsResponse.decode(value),
  },
} as const;

export interface BankServiceServer extends UntypedServiceImplementation {
  createUser: handleUnaryCall<CreateUserRequest, CreateUserResponse>;
  transferMoney: handleUnaryCall<TransferRequest, TransferResponse>;
  getBalance: handleUnaryCall<BalanceRequest, BalanceResponse>;
  getHistory: handleUnaryCall<HistoryRequest, HistoryResponse>;
  /**
   * Admin dashboard read-only audit log listing. Trust boundary: this RPC is
   * only reachable on the internal TLS gRPC network; admin authn/authz happens
   * at the API Gateway before it forwards the call.
   */
  listAuditEvents: handleUnaryCall<ListAuditEventsRequest, ListAuditEventsResponse>;
}

export interface BankServiceClient extends Client {
  createUser(
    request: CreateUserRequest,
    callback: (error: ServiceError | null, response: CreateUserResponse) => void,
  ): ClientUnaryCall;
  createUser(
    request: CreateUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateUserResponse) => void,
  ): ClientUnaryCall;
  createUser(
    request: CreateUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateUserResponse) => void,
  ): ClientUnaryCall;
  transferMoney(
    request: TransferRequest,
    callback: (error: ServiceError | null, response: TransferResponse) => void,
  ): ClientUnaryCall;
  transferMoney(
    request: TransferRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: TransferResponse) => void,
  ): ClientUnaryCall;
  transferMoney(
    request: TransferRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: TransferResponse) => void,
  ): ClientUnaryCall;
  getBalance(
    request: BalanceRequest,
    callback: (error: ServiceError | null, response: BalanceResponse) => void,
  ): ClientUnaryCall;
  getBalance(
    request: BalanceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: BalanceResponse) => void,
  ): ClientUnaryCall;
  getBalance(
    request: BalanceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: BalanceResponse) => void,
  ): ClientUnaryCall;
  getHistory(
    request: HistoryRequest,
    callback: (error: ServiceError | null, response: HistoryResponse) => void,
  ): ClientUnaryCall;
  getHistory(
    request: HistoryRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HistoryResponse) => void,
  ): ClientUnaryCall;
  getHistory(
    request: HistoryRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HistoryResponse) => void,
  ): ClientUnaryCall;
  /**
   * Admin dashboard read-only audit log listing. Trust boundary: this RPC is
   * only reachable on the internal TLS gRPC network; admin authn/authz happens
   * at the API Gateway before it forwards the call.
   */
  listAuditEvents(
    request: ListAuditEventsRequest,
    callback: (error: ServiceError | null, response: ListAuditEventsResponse) => void,
  ): ClientUnaryCall;
  listAuditEvents(
    request: ListAuditEventsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListAuditEventsResponse) => void,
  ): ClientUnaryCall;
  listAuditEvents(
    request: ListAuditEventsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListAuditEventsResponse) => void,
  ): ClientUnaryCall;
}

export const BankServiceClient = makeGenericClientConstructor(BankServiceService, "bank.BankService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): BankServiceClient;
  service: typeof BankServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
