// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: ca.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "ca";

export enum CertStatus {
  CERT_STATUS_UNKNOWN = 0,
  CERT_STATUS_ACTIVE = 1,
  CERT_STATUS_REVOKED = 2,
  CERT_STATUS_EXPIRED = 3,
  UNRECOGNIZED = -1,
}

export function certStatusFromJSON(object: any): CertStatus {
  switch (object) {
    case 0:
    case "CERT_STATUS_UNKNOWN":
      return CertStatus.CERT_STATUS_UNKNOWN;
    case 1:
    case "CERT_STATUS_ACTIVE":
      return CertStatus.CERT_STATUS_ACTIVE;
    case 2:
    case "CERT_STATUS_REVOKED":
      return CertStatus.CERT_STATUS_REVOKED;
    case 3:
    case "CERT_STATUS_EXPIRED":
      return CertStatus.CERT_STATUS_EXPIRED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CertStatus.UNRECOGNIZED;
  }
}

export function certStatusToJSON(object: CertStatus): string {
  switch (object) {
    case CertStatus.CERT_STATUS_UNKNOWN:
      return "CERT_STATUS_UNKNOWN";
    case CertStatus.CERT_STATUS_ACTIVE:
      return "CERT_STATUS_ACTIVE";
    case CertStatus.CERT_STATUS_REVOKED:
      return "CERT_STATUS_REVOKED";
    case CertStatus.CERT_STATUS_EXPIRED:
      return "CERT_STATUS_EXPIRED";
    case CertStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CertificateMetadata {
  serialNumber: string;
  ownerId: string;
  subjectCn: string;
  subjectEmail: string;
  fingerprintSha256: string;
  status: CertStatus;
  notBeforeUnix: number;
  notAfterUnix: number;
  issuedAtUnix: number;
  revokedAtUnix: number;
  revocationReason: string;
}

export interface RegisterUserRequest {
  csrPem: string;
  ownerId: string;
  subjectCn: string;
  subjectEmail: string;
  requestId: string;
  performedBy: string;
}

export interface RegisterUserResponse {
  certificatePem: string;
  serialNumber: string;
  notBeforeUnix: number;
  notAfterUnix: number;
  fingerprintSha256: string;
}

export interface VerifyCertificateRequest {
  serialNumber: string;
  requestId: string;
  caller: string;
  includeCertificatePem: boolean;
  includePublicKeyPem: boolean;
}

export interface VerifyCertificateResponse {
  status: CertStatus;
  ownerId: string;
  certificatePem: string;
  publicKeyPem: string;
  fingerprintSha256: string;
  notBeforeUnix: number;
  notAfterUnix: number;
  revokedAtUnix: number;
  revocationReason: string;
}

export interface GetCertificateRequest {
  serialNumber: string;
}

export interface GetCertificateResponse {
  certificatePem: string;
  userId: string;
  status: CertStatus;
  notAfterUnix: number;
  publicKeyPem: string;
}

export interface CheckRevocationRequest {
  serialNumber: string;
}

export interface CheckRevocationResponse {
  status: CertStatus;
  reason: string;
  revokedAt: number;
}

export interface ListCertificatesRequest {
  status: string;
  email: string;
  serialNumber: string;
  limit: number;
  offset: number;
  requestId: string;
  performedBy: string;
}

export interface ListCertificatesResponse {
  certificates: CertificateMetadata[];
  total: number;
  limit: number;
  offset: number;
}

export interface GetCertificateDetailRequest {
  serialNumber: string;
  requestId: string;
  performedBy: string;
}

export interface GetCertificateDetailResponse {
  certificate?: CertificateMetadata | undefined;
}

export interface RevokeCertificateRequest {
  serialNumber: string;
  reason: string;
  requestId: string;
  performedBy: string;
}

export interface RevokeCertificateResponse {
  certificate?: CertificateMetadata | undefined;
}

function createBaseCertificateMetadata(): CertificateMetadata {
  return {
    serialNumber: "",
    ownerId: "",
    subjectCn: "",
    subjectEmail: "",
    fingerprintSha256: "",
    status: 0,
    notBeforeUnix: 0,
    notAfterUnix: 0,
    issuedAtUnix: 0,
    revokedAtUnix: 0,
    revocationReason: "",
  };
}

export const CertificateMetadata: MessageFns<CertificateMetadata> = {
  encode(message: CertificateMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serialNumber !== "") {
      writer.uint32(10).string(message.serialNumber);
    }
    if (message.ownerId !== "") {
      writer.uint32(18).string(message.ownerId);
    }
    if (message.subjectCn !== "") {
      writer.uint32(26).string(message.subjectCn);
    }
    if (message.subjectEmail !== "") {
      writer.uint32(34).string(message.subjectEmail);
    }
    if (message.fingerprintSha256 !== "") {
      writer.uint32(42).string(message.fingerprintSha256);
    }
    if (message.status !== 0) {
      writer.uint32(48).int32(message.status);
    }
    if (message.notBeforeUnix !== 0) {
      writer.uint32(56).int64(message.notBeforeUnix);
    }
    if (message.notAfterUnix !== 0) {
      writer.uint32(64).int64(message.notAfterUnix);
    }
    if (message.issuedAtUnix !== 0) {
      writer.uint32(72).int64(message.issuedAtUnix);
    }
    if (message.revokedAtUnix !== 0) {
      writer.uint32(80).int64(message.revokedAtUnix);
    }
    if (message.revocationReason !== "") {
      writer.uint32(90).string(message.revocationReason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CertificateMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCertificateMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serialNumber = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ownerId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.subjectCn = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.subjectEmail = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.fingerprintSha256 = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.notBeforeUnix = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.notAfterUnix = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.issuedAtUnix = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.revokedAtUnix = longToNumber(reader.int64());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.revocationReason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CertificateMetadata {
    return {
      serialNumber: isSet(object.serialNumber)
        ? globalThis.String(object.serialNumber)
        : isSet(object.serial_number)
        ? globalThis.String(object.serial_number)
        : "",
      ownerId: isSet(object.ownerId)
        ? globalThis.String(object.ownerId)
        : isSet(object.owner_id)
        ? globalThis.String(object.owner_id)
        : "",
      subjectCn: isSet(object.subjectCn)
        ? globalThis.String(object.subjectCn)
        : isSet(object.subject_cn)
        ? globalThis.String(object.subject_cn)
        : "",
      subjectEmail: isSet(object.subjectEmail)
        ? globalThis.String(object.subjectEmail)
        : isSet(object.subject_email)
        ? globalThis.String(object.subject_email)
        : "",
      fingerprintSha256: isSet(object.fingerprintSha256)
        ? globalThis.String(object.fingerprintSha256)
        : isSet(object.fingerprint_sha256)
        ? globalThis.String(object.fingerprint_sha256)
        : "",
      status: isSet(object.status) ? certStatusFromJSON(object.status) : 0,
      notBeforeUnix: isSet(object.notBeforeUnix)
        ? globalThis.Number(object.notBeforeUnix)
        : isSet(object.not_before_unix)
        ? globalThis.Number(object.not_before_unix)
        : 0,
      notAfterUnix: isSet(object.notAfterUnix)
        ? globalThis.Number(object.notAfterUnix)
        : isSet(object.not_after_unix)
        ? globalThis.Number(object.not_after_unix)
        : 0,
      issuedAtUnix: isSet(object.issuedAtUnix)
        ? globalThis.Number(object.issuedAtUnix)
        : isSet(object.issued_at_unix)
        ? globalThis.Number(object.issued_at_unix)
        : 0,
      revokedAtUnix: isSet(object.revokedAtUnix)
        ? globalThis.Number(object.revokedAtUnix)
        : isSet(object.revoked_at_unix)
        ? globalThis.Number(object.revoked_at_unix)
        : 0,
      revocationReason: isSet(object.revocationReason)
        ? globalThis.String(object.revocationReason)
        : isSet(object.revocation_reason)
        ? globalThis.String(object.revocation_reason)
        : "",
    };
  },

  toJSON(message: CertificateMetadata): unknown {
    const obj: any = {};
    if (message.serialNumber !== "") {
      obj.serialNumber = message.serialNumber;
    }
    if (message.ownerId !== "") {
      obj.ownerId = message.ownerId;
    }
    if (message.subjectCn !== "") {
      obj.subjectCn = message.subjectCn;
    }
    if (message.subjectEmail !== "") {
      obj.subjectEmail = message.subjectEmail;
    }
    if (message.fingerprintSha256 !== "") {
      obj.fingerprintSha256 = message.fingerprintSha256;
    }
    if (message.status !== 0) {
      obj.status = certStatusToJSON(message.status);
    }
    if (message.notBeforeUnix !== 0) {
      obj.notBeforeUnix = Math.round(message.notBeforeUnix);
    }
    if (message.notAfterUnix !== 0) {
      obj.notAfterUnix = Math.round(message.notAfterUnix);
    }
    if (message.issuedAtUnix !== 0) {
      obj.issuedAtUnix = Math.round(message.issuedAtUnix);
    }
    if (message.revokedAtUnix !== 0) {
      obj.revokedAtUnix = Math.round(message.revokedAtUnix);
    }
    if (message.revocationReason !== "") {
      obj.revocationReason = message.revocationReason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CertificateMetadata>, I>>(base?: I): CertificateMetadata {
    return CertificateMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CertificateMetadata>, I>>(object: I): CertificateMetadata {
    const message = createBaseCertificateMetadata();
    message.serialNumber = object.serialNumber ?? "";
    message.ownerId = object.ownerId ?? "";
    message.subjectCn = object.subjectCn ?? "";
    message.subjectEmail = object.subjectEmail ?? "";
    message.fingerprintSha256 = object.fingerprintSha256 ?? "";
    message.status = object.status ?? 0;
    message.notBeforeUnix = object.notBeforeUnix ?? 0;
    message.notAfterUnix = object.notAfterUnix ?? 0;
    message.issuedAtUnix = object.issuedAtUnix ?? 0;
    message.revokedAtUnix = object.revokedAtUnix ?? 0;
    message.revocationReason = object.revocationReason ?? "";
    return message;
  },
};

function createBaseRegisterUserRequest(): RegisterUserRequest {
  return { csrPem: "", ownerId: "", subjectCn: "", subjectEmail: "", requestId: "", performedBy: "" };
}

export const RegisterUserRequest: MessageFns<RegisterUserRequest> = {
  encode(message: RegisterUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.csrPem !== "") {
      writer.uint32(10).string(message.csrPem);
    }
    if (message.ownerId !== "") {
      writer.uint32(18).string(message.ownerId);
    }
    if (message.subjectCn !== "") {
      writer.uint32(26).string(message.subjectCn);
    }
    if (message.subjectEmail !== "") {
      writer.uint32(34).string(message.subjectEmail);
    }
    if (message.requestId !== "") {
      writer.uint32(42).string(message.requestId);
    }
    if (message.performedBy !== "") {
      writer.uint32(50).string(message.performedBy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.csrPem = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ownerId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.subjectCn = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.subjectEmail = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.performedBy = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterUserRequest {
    return {
      csrPem: isSet(object.csrPem)
        ? globalThis.String(object.csrPem)
        : isSet(object.csr_pem)
        ? globalThis.String(object.csr_pem)
        : "",
      ownerId: isSet(object.ownerId)
        ? globalThis.String(object.ownerId)
        : isSet(object.owner_id)
        ? globalThis.String(object.owner_id)
        : "",
      subjectCn: isSet(object.subjectCn)
        ? globalThis.String(object.subjectCn)
        : isSet(object.subject_cn)
        ? globalThis.String(object.subject_cn)
        : "",
      subjectEmail: isSet(object.subjectEmail)
        ? globalThis.String(object.subjectEmail)
        : isSet(object.subject_email)
        ? globalThis.String(object.subject_email)
        : "",
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      performedBy: isSet(object.performedBy)
        ? globalThis.String(object.performedBy)
        : isSet(object.performed_by)
        ? globalThis.String(object.performed_by)
        : "",
    };
  },

  toJSON(message: RegisterUserRequest): unknown {
    const obj: any = {};
    if (message.csrPem !== "") {
      obj.csrPem = message.csrPem;
    }
    if (message.ownerId !== "") {
      obj.ownerId = message.ownerId;
    }
    if (message.subjectCn !== "") {
      obj.subjectCn = message.subjectCn;
    }
    if (message.subjectEmail !== "") {
      obj.subjectEmail = message.subjectEmail;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.performedBy !== "") {
      obj.performedBy = message.performedBy;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterUserRequest>, I>>(base?: I): RegisterUserRequest {
    return RegisterUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterUserRequest>, I>>(object: I): RegisterUserRequest {
    const message = createBaseRegisterUserRequest();
    message.csrPem = object.csrPem ?? "";
    message.ownerId = object.ownerId ?? "";
    message.subjectCn = object.subjectCn ?? "";
    message.subjectEmail = object.subjectEmail ?? "";
    message.requestId = object.requestId ?? "";
    message.performedBy = object.performedBy ?? "";
    return message;
  },
};

function createBaseRegisterUserResponse(): RegisterUserResponse {
  return { certificatePem: "", serialNumber: "", notBeforeUnix: 0, notAfterUnix: 0, fingerprintSha256: "" };
}

export const RegisterUserResponse: MessageFns<RegisterUserResponse> = {
  encode(message: RegisterUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.certificatePem !== "") {
      writer.uint32(10).string(message.certificatePem);
    }
    if (message.serialNumber !== "") {
      writer.uint32(18).string(message.serialNumber);
    }
    if (message.notBeforeUnix !== 0) {
      writer.uint32(24).int64(message.notBeforeUnix);
    }
    if (message.notAfterUnix !== 0) {
      writer.uint32(32).int64(message.notAfterUnix);
    }
    if (message.fingerprintSha256 !== "") {
      writer.uint32(42).string(message.fingerprintSha256);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.certificatePem = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serialNumber = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.notBeforeUnix = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.notAfterUnix = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.fingerprintSha256 = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterUserResponse {
    return {
      certificatePem: isSet(object.certificatePem)
        ? globalThis.String(object.certificatePem)
        : isSet(object.certificate_pem)
        ? globalThis.String(object.certificate_pem)
        : "",
      serialNumber: isSet(object.serialNumber)
        ? globalThis.String(object.serialNumber)
        : isSet(object.serial_number)
        ? globalThis.String(object.serial_number)
        : "",
      notBeforeUnix: isSet(object.notBeforeUnix)
        ? globalThis.Number(object.notBeforeUnix)
        : isSet(object.not_before_unix)
        ? globalThis.Number(object.not_before_unix)
        : 0,
      notAfterUnix: isSet(object.notAfterUnix)
        ? globalThis.Number(object.notAfterUnix)
        : isSet(object.not_after_unix)
        ? globalThis.Number(object.not_after_unix)
        : 0,
      fingerprintSha256: isSet(object.fingerprintSha256)
        ? globalThis.String(object.fingerprintSha256)
        : isSet(object.fingerprint_sha256)
        ? globalThis.String(object.fingerprint_sha256)
        : "",
    };
  },

  toJSON(message: RegisterUserResponse): unknown {
    const obj: any = {};
    if (message.certificatePem !== "") {
      obj.certificatePem = message.certificatePem;
    }
    if (message.serialNumber !== "") {
      obj.serialNumber = message.serialNumber;
    }
    if (message.notBeforeUnix !== 0) {
      obj.notBeforeUnix = Math.round(message.notBeforeUnix);
    }
    if (message.notAfterUnix !== 0) {
      obj.notAfterUnix = Math.round(message.notAfterUnix);
    }
    if (message.fingerprintSha256 !== "") {
      obj.fingerprintSha256 = message.fingerprintSha256;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterUserResponse>, I>>(base?: I): RegisterUserResponse {
    return RegisterUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterUserResponse>, I>>(object: I): RegisterUserResponse {
    const message = createBaseRegisterUserResponse();
    message.certificatePem = object.certificatePem ?? "";
    message.serialNumber = object.serialNumber ?? "";
    message.notBeforeUnix = object.notBeforeUnix ?? 0;
    message.notAfterUnix = object.notAfterUnix ?? 0;
    message.fingerprintSha256 = object.fingerprintSha256 ?? "";
    return message;
  },
};

function createBaseVerifyCertificateRequest(): VerifyCertificateRequest {
  return { serialNumber: "", requestId: "", caller: "", includeCertificatePem: false, includePublicKeyPem: false };
}

export const VerifyCertificateRequest: MessageFns<VerifyCertificateRequest> = {
  encode(message: VerifyCertificateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serialNumber !== "") {
      writer.uint32(10).string(message.serialNumber);
    }
    if (message.requestId !== "") {
      writer.uint32(18).string(message.requestId);
    }
    if (message.caller !== "") {
      writer.uint32(26).string(message.caller);
    }
    if (message.includeCertificatePem !== false) {
      writer.uint32(32).bool(message.includeCertificatePem);
    }
    if (message.includePublicKeyPem !== false) {
      writer.uint32(40).bool(message.includePublicKeyPem);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyCertificateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyCertificateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serialNumber = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.caller = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.includeCertificatePem = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.includePublicKeyPem = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VerifyCertificateRequest {
    return {
      serialNumber: isSet(object.serialNumber)
        ? globalThis.String(object.serialNumber)
        : isSet(object.serial_number)
        ? globalThis.String(object.serial_number)
        : "",
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      caller: isSet(object.caller) ? globalThis.String(object.caller) : "",
      includeCertificatePem: isSet(object.includeCertificatePem)
        ? globalThis.Boolean(object.includeCertificatePem)
        : isSet(object.include_certificate_pem)
        ? globalThis.Boolean(object.include_certificate_pem)
        : false,
      includePublicKeyPem: isSet(object.includePublicKeyPem)
        ? globalThis.Boolean(object.includePublicKeyPem)
        : isSet(object.include_public_key_pem)
        ? globalThis.Boolean(object.include_public_key_pem)
        : false,
    };
  },

  toJSON(message: VerifyCertificateRequest): unknown {
    const obj: any = {};
    if (message.serialNumber !== "") {
      obj.serialNumber = message.serialNumber;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.caller !== "") {
      obj.caller = message.caller;
    }
    if (message.includeCertificatePem !== false) {
      obj.includeCertificatePem = message.includeCertificatePem;
    }
    if (message.includePublicKeyPem !== false) {
      obj.includePublicKeyPem = message.includePublicKeyPem;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VerifyCertificateRequest>, I>>(base?: I): VerifyCertificateRequest {
    return VerifyCertificateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyCertificateRequest>, I>>(object: I): VerifyCertificateRequest {
    const message = createBaseVerifyCertificateRequest();
    message.serialNumber = object.serialNumber ?? "";
    message.requestId = object.requestId ?? "";
    message.caller = object.caller ?? "";
    message.includeCertificatePem = object.includeCertificatePem ?? false;
    message.includePublicKeyPem = object.includePublicKeyPem ?? false;
    return message;
  },
};

function createBaseVerifyCertificateResponse(): VerifyCertificateResponse {
  return {
    status: 0,
    ownerId: "",
    certificatePem: "",
    publicKeyPem: "",
    fingerprintSha256: "",
    notBeforeUnix: 0,
    notAfterUnix: 0,
    revokedAtUnix: 0,
    revocationReason: "",
  };
}

export const VerifyCertificateResponse: MessageFns<VerifyCertificateResponse> = {
  encode(message: VerifyCertificateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.ownerId !== "") {
      writer.uint32(18).string(message.ownerId);
    }
    if (message.certificatePem !== "") {
      writer.uint32(26).string(message.certificatePem);
    }
    if (message.publicKeyPem !== "") {
      writer.uint32(34).string(message.publicKeyPem);
    }
    if (message.fingerprintSha256 !== "") {
      writer.uint32(42).string(message.fingerprintSha256);
    }
    if (message.notBeforeUnix !== 0) {
      writer.uint32(48).int64(message.notBeforeUnix);
    }
    if (message.notAfterUnix !== 0) {
      writer.uint32(56).int64(message.notAfterUnix);
    }
    if (message.revokedAtUnix !== 0) {
      writer.uint32(64).int64(message.revokedAtUnix);
    }
    if (message.revocationReason !== "") {
      writer.uint32(74).string(message.revocationReason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyCertificateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyCertificateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ownerId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.certificatePem = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.publicKeyPem = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.fingerprintSha256 = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.notBeforeUnix = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.notAfterUnix = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.revokedAtUnix = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.revocationReason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VerifyCertificateResponse {
    return {
      status: isSet(object.status) ? certStatusFromJSON(object.status) : 0,
      ownerId: isSet(object.ownerId)
        ? globalThis.String(object.ownerId)
        : isSet(object.owner_id)
        ? globalThis.String(object.owner_id)
        : "",
      certificatePem: isSet(object.certificatePem)
        ? globalThis.String(object.certificatePem)
        : isSet(object.certificate_pem)
        ? globalThis.String(object.certificate_pem)
        : "",
      publicKeyPem: isSet(object.publicKeyPem)
        ? globalThis.String(object.publicKeyPem)
        : isSet(object.public_key_pem)
        ? globalThis.String(object.public_key_pem)
        : "",
      fingerprintSha256: isSet(object.fingerprintSha256)
        ? globalThis.String(object.fingerprintSha256)
        : isSet(object.fingerprint_sha256)
        ? globalThis.String(object.fingerprint_sha256)
        : "",
      notBeforeUnix: isSet(object.notBeforeUnix)
        ? globalThis.Number(object.notBeforeUnix)
        : isSet(object.not_before_unix)
        ? globalThis.Number(object.not_before_unix)
        : 0,
      notAfterUnix: isSet(object.notAfterUnix)
        ? globalThis.Number(object.notAfterUnix)
        : isSet(object.not_after_unix)
        ? globalThis.Number(object.not_after_unix)
        : 0,
      revokedAtUnix: isSet(object.revokedAtUnix)
        ? globalThis.Number(object.revokedAtUnix)
        : isSet(object.revoked_at_unix)
        ? globalThis.Number(object.revoked_at_unix)
        : 0,
      revocationReason: isSet(object.revocationReason)
        ? globalThis.String(object.revocationReason)
        : isSet(object.revocation_reason)
        ? globalThis.String(object.revocation_reason)
        : "",
    };
  },

  toJSON(message: VerifyCertificateResponse): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = certStatusToJSON(message.status);
    }
    if (message.ownerId !== "") {
      obj.ownerId = message.ownerId;
    }
    if (message.certificatePem !== "") {
      obj.certificatePem = message.certificatePem;
    }
    if (message.publicKeyPem !== "") {
      obj.publicKeyPem = message.publicKeyPem;
    }
    if (message.fingerprintSha256 !== "") {
      obj.fingerprintSha256 = message.fingerprintSha256;
    }
    if (message.notBeforeUnix !== 0) {
      obj.notBeforeUnix = Math.round(message.notBeforeUnix);
    }
    if (message.notAfterUnix !== 0) {
      obj.notAfterUnix = Math.round(message.notAfterUnix);
    }
    if (message.revokedAtUnix !== 0) {
      obj.revokedAtUnix = Math.round(message.revokedAtUnix);
    }
    if (message.revocationReason !== "") {
      obj.revocationReason = message.revocationReason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VerifyCertificateResponse>, I>>(base?: I): VerifyCertificateResponse {
    return VerifyCertificateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyCertificateResponse>, I>>(object: I): VerifyCertificateResponse {
    const message = createBaseVerifyCertificateResponse();
    message.status = object.status ?? 0;
    message.ownerId = object.ownerId ?? "";
    message.certificatePem = object.certificatePem ?? "";
    message.publicKeyPem = object.publicKeyPem ?? "";
    message.fingerprintSha256 = object.fingerprintSha256 ?? "";
    message.notBeforeUnix = object.notBeforeUnix ?? 0;
    message.notAfterUnix = object.notAfterUnix ?? 0;
    message.revokedAtUnix = object.revokedAtUnix ?? 0;
    message.revocationReason = object.revocationReason ?? "";
    return message;
  },
};

function createBaseGetCertificateRequest(): GetCertificateRequest {
  return { serialNumber: "" };
}

export const GetCertificateRequest: MessageFns<GetCertificateRequest> = {
  encode(message: GetCertificateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serialNumber !== "") {
      writer.uint32(10).string(message.serialNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCertificateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCertificateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serialNumber = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCertificateRequest {
    return {
      serialNumber: isSet(object.serialNumber)
        ? globalThis.String(object.serialNumber)
        : isSet(object.serial_number)
        ? globalThis.String(object.serial_number)
        : "",
    };
  },

  toJSON(message: GetCertificateRequest): unknown {
    const obj: any = {};
    if (message.serialNumber !== "") {
      obj.serialNumber = message.serialNumber;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCertificateRequest>, I>>(base?: I): GetCertificateRequest {
    return GetCertificateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCertificateRequest>, I>>(object: I): GetCertificateRequest {
    const message = createBaseGetCertificateRequest();
    message.serialNumber = object.serialNumber ?? "";
    return message;
  },
};

function createBaseGetCertificateResponse(): GetCertificateResponse {
  return { certificatePem: "", userId: "", status: 0, notAfterUnix: 0, publicKeyPem: "" };
}

export const GetCertificateResponse: MessageFns<GetCertificateResponse> = {
  encode(message: GetCertificateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.certificatePem !== "") {
      writer.uint32(10).string(message.certificatePem);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.status !== 0) {
      writer.uint32(24).int32(message.status);
    }
    if (message.notAfterUnix !== 0) {
      writer.uint32(32).int64(message.notAfterUnix);
    }
    if (message.publicKeyPem !== "") {
      writer.uint32(42).string(message.publicKeyPem);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCertificateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCertificateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.certificatePem = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.notAfterUnix = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.publicKeyPem = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCertificateResponse {
    return {
      certificatePem: isSet(object.certificatePem)
        ? globalThis.String(object.certificatePem)
        : isSet(object.certificate_pem)
        ? globalThis.String(object.certificate_pem)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      status: isSet(object.status) ? certStatusFromJSON(object.status) : 0,
      notAfterUnix: isSet(object.notAfterUnix)
        ? globalThis.Number(object.notAfterUnix)
        : isSet(object.not_after_unix)
        ? globalThis.Number(object.not_after_unix)
        : 0,
      publicKeyPem: isSet(object.publicKeyPem)
        ? globalThis.String(object.publicKeyPem)
        : isSet(object.public_key_pem)
        ? globalThis.String(object.public_key_pem)
        : "",
    };
  },

  toJSON(message: GetCertificateResponse): unknown {
    const obj: any = {};
    if (message.certificatePem !== "") {
      obj.certificatePem = message.certificatePem;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.status !== 0) {
      obj.status = certStatusToJSON(message.status);
    }
    if (message.notAfterUnix !== 0) {
      obj.notAfterUnix = Math.round(message.notAfterUnix);
    }
    if (message.publicKeyPem !== "") {
      obj.publicKeyPem = message.publicKeyPem;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCertificateResponse>, I>>(base?: I): GetCertificateResponse {
    return GetCertificateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCertificateResponse>, I>>(object: I): GetCertificateResponse {
    const message = createBaseGetCertificateResponse();
    message.certificatePem = object.certificatePem ?? "";
    message.userId = object.userId ?? "";
    message.status = object.status ?? 0;
    message.notAfterUnix = object.notAfterUnix ?? 0;
    message.publicKeyPem = object.publicKeyPem ?? "";
    return message;
  },
};

function createBaseCheckRevocationRequest(): CheckRevocationRequest {
  return { serialNumber: "" };
}

export const CheckRevocationRequest: MessageFns<CheckRevocationRequest> = {
  encode(message: CheckRevocationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serialNumber !== "") {
      writer.uint32(10).string(message.serialNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckRevocationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckRevocationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serialNumber = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckRevocationRequest {
    return {
      serialNumber: isSet(object.serialNumber)
        ? globalThis.String(object.serialNumber)
        : isSet(object.serial_number)
        ? globalThis.String(object.serial_number)
        : "",
    };
  },

  toJSON(message: CheckRevocationRequest): unknown {
    const obj: any = {};
    if (message.serialNumber !== "") {
      obj.serialNumber = message.serialNumber;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckRevocationRequest>, I>>(base?: I): CheckRevocationRequest {
    return CheckRevocationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckRevocationRequest>, I>>(object: I): CheckRevocationRequest {
    const message = createBaseCheckRevocationRequest();
    message.serialNumber = object.serialNumber ?? "";
    return message;
  },
};

function createBaseCheckRevocationResponse(): CheckRevocationResponse {
  return { status: 0, reason: "", revokedAt: 0 };
}

export const CheckRevocationResponse: MessageFns<CheckRevocationResponse> = {
  encode(message: CheckRevocationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    if (message.revokedAt !== 0) {
      writer.uint32(24).int64(message.revokedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckRevocationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckRevocationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.revokedAt = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckRevocationResponse {
    return {
      status: isSet(object.status) ? certStatusFromJSON(object.status) : 0,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      revokedAt: isSet(object.revokedAt)
        ? globalThis.Number(object.revokedAt)
        : isSet(object.revoked_at)
        ? globalThis.Number(object.revoked_at)
        : 0,
    };
  },

  toJSON(message: CheckRevocationResponse): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = certStatusToJSON(message.status);
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.revokedAt !== 0) {
      obj.revokedAt = Math.round(message.revokedAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckRevocationResponse>, I>>(base?: I): CheckRevocationResponse {
    return CheckRevocationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckRevocationResponse>, I>>(object: I): CheckRevocationResponse {
    const message = createBaseCheckRevocationResponse();
    message.status = object.status ?? 0;
    message.reason = object.reason ?? "";
    message.revokedAt = object.revokedAt ?? 0;
    return message;
  },
};

function createBaseListCertificatesRequest(): ListCertificatesRequest {
  return { status: "", email: "", serialNumber: "", limit: 0, offset: 0, requestId: "", performedBy: "" };
}

export const ListCertificatesRequest: MessageFns<ListCertificatesRequest> = {
  encode(message: ListCertificatesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.serialNumber !== "") {
      writer.uint32(26).string(message.serialNumber);
    }
    if (message.limit !== 0) {
      writer.uint32(32).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(40).int32(message.offset);
    }
    if (message.requestId !== "") {
      writer.uint32(50).string(message.requestId);
    }
    if (message.performedBy !== "") {
      writer.uint32(58).string(message.performedBy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListCertificatesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListCertificatesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.serialNumber = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.performedBy = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListCertificatesRequest {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      serialNumber: isSet(object.serialNumber)
        ? globalThis.String(object.serialNumber)
        : isSet(object.serial_number)
        ? globalThis.String(object.serial_number)
        : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      performedBy: isSet(object.performedBy)
        ? globalThis.String(object.performedBy)
        : isSet(object.performed_by)
        ? globalThis.String(object.performed_by)
        : "",
    };
  },

  toJSON(message: ListCertificatesRequest): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.serialNumber !== "") {
      obj.serialNumber = message.serialNumber;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.performedBy !== "") {
      obj.performedBy = message.performedBy;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListCertificatesRequest>, I>>(base?: I): ListCertificatesRequest {
    return ListCertificatesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListCertificatesRequest>, I>>(object: I): ListCertificatesRequest {
    const message = createBaseListCertificatesRequest();
    message.status = object.status ?? "";
    message.email = object.email ?? "";
    message.serialNumber = object.serialNumber ?? "";
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    message.requestId = object.requestId ?? "";
    message.performedBy = object.performedBy ?? "";
    return message;
  },
};

function createBaseListCertificatesResponse(): ListCertificatesResponse {
  return { certificates: [], total: 0, limit: 0, offset: 0 };
}

export const ListCertificatesResponse: MessageFns<ListCertificatesResponse> = {
  encode(message: ListCertificatesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.certificates) {
      CertificateMetadata.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(32).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListCertificatesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListCertificatesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.certificates.push(CertificateMetadata.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListCertificatesResponse {
    return {
      certificates: globalThis.Array.isArray(object?.certificates)
        ? object.certificates.map((e: any) => CertificateMetadata.fromJSON(e))
        : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
    };
  },

  toJSON(message: ListCertificatesResponse): unknown {
    const obj: any = {};
    if (message.certificates?.length) {
      obj.certificates = message.certificates.map((e) => CertificateMetadata.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListCertificatesResponse>, I>>(base?: I): ListCertificatesResponse {
    return ListCertificatesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListCertificatesResponse>, I>>(object: I): ListCertificatesResponse {
    const message = createBaseListCertificatesResponse();
    message.certificates = object.certificates?.map((e) => CertificateMetadata.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    return message;
  },
};

function createBaseGetCertificateDetailRequest(): GetCertificateDetailRequest {
  return { serialNumber: "", requestId: "", performedBy: "" };
}

export const GetCertificateDetailRequest: MessageFns<GetCertificateDetailRequest> = {
  encode(message: GetCertificateDetailRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serialNumber !== "") {
      writer.uint32(10).string(message.serialNumber);
    }
    if (message.requestId !== "") {
      writer.uint32(18).string(message.requestId);
    }
    if (message.performedBy !== "") {
      writer.uint32(26).string(message.performedBy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCertificateDetailRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCertificateDetailRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serialNumber = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.performedBy = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCertificateDetailRequest {
    return {
      serialNumber: isSet(object.serialNumber)
        ? globalThis.String(object.serialNumber)
        : isSet(object.serial_number)
        ? globalThis.String(object.serial_number)
        : "",
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      performedBy: isSet(object.performedBy)
        ? globalThis.String(object.performedBy)
        : isSet(object.performed_by)
        ? globalThis.String(object.performed_by)
        : "",
    };
  },

  toJSON(message: GetCertificateDetailRequest): unknown {
    const obj: any = {};
    if (message.serialNumber !== "") {
      obj.serialNumber = message.serialNumber;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.performedBy !== "") {
      obj.performedBy = message.performedBy;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCertificateDetailRequest>, I>>(base?: I): GetCertificateDetailRequest {
    return GetCertificateDetailRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCertificateDetailRequest>, I>>(object: I): GetCertificateDetailRequest {
    const message = createBaseGetCertificateDetailRequest();
    message.serialNumber = object.serialNumber ?? "";
    message.requestId = object.requestId ?? "";
    message.performedBy = object.performedBy ?? "";
    return message;
  },
};

function createBaseGetCertificateDetailResponse(): GetCertificateDetailResponse {
  return { certificate: undefined };
}

export const GetCertificateDetailResponse: MessageFns<GetCertificateDetailResponse> = {
  encode(message: GetCertificateDetailResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.certificate !== undefined) {
      CertificateMetadata.encode(message.certificate, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCertificateDetailResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCertificateDetailResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.certificate = CertificateMetadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCertificateDetailResponse {
    return { certificate: isSet(object.certificate) ? CertificateMetadata.fromJSON(object.certificate) : undefined };
  },

  toJSON(message: GetCertificateDetailResponse): unknown {
    const obj: any = {};
    if (message.certificate !== undefined) {
      obj.certificate = CertificateMetadata.toJSON(message.certificate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCertificateDetailResponse>, I>>(base?: I): GetCertificateDetailResponse {
    return GetCertificateDetailResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCertificateDetailResponse>, I>>(object: I): GetCertificateDetailResponse {
    const message = createBaseGetCertificateDetailResponse();
    message.certificate = (object.certificate !== undefined && object.certificate !== null)
      ? CertificateMetadata.fromPartial(object.certificate)
      : undefined;
    return message;
  },
};

function createBaseRevokeCertificateRequest(): RevokeCertificateRequest {
  return { serialNumber: "", reason: "", requestId: "", performedBy: "" };
}

export const RevokeCertificateRequest: MessageFns<RevokeCertificateRequest> = {
  encode(message: RevokeCertificateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serialNumber !== "") {
      writer.uint32(10).string(message.serialNumber);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    if (message.requestId !== "") {
      writer.uint32(26).string(message.requestId);
    }
    if (message.performedBy !== "") {
      writer.uint32(34).string(message.performedBy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RevokeCertificateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRevokeCertificateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serialNumber = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.performedBy = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RevokeCertificateRequest {
    return {
      serialNumber: isSet(object.serialNumber)
        ? globalThis.String(object.serialNumber)
        : isSet(object.serial_number)
        ? globalThis.String(object.serial_number)
        : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      performedBy: isSet(object.performedBy)
        ? globalThis.String(object.performedBy)
        : isSet(object.performed_by)
        ? globalThis.String(object.performed_by)
        : "",
    };
  },

  toJSON(message: RevokeCertificateRequest): unknown {
    const obj: any = {};
    if (message.serialNumber !== "") {
      obj.serialNumber = message.serialNumber;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.performedBy !== "") {
      obj.performedBy = message.performedBy;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RevokeCertificateRequest>, I>>(base?: I): RevokeCertificateRequest {
    return RevokeCertificateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RevokeCertificateRequest>, I>>(object: I): RevokeCertificateRequest {
    const message = createBaseRevokeCertificateRequest();
    message.serialNumber = object.serialNumber ?? "";
    message.reason = object.reason ?? "";
    message.requestId = object.requestId ?? "";
    message.performedBy = object.performedBy ?? "";
    return message;
  },
};

function createBaseRevokeCertificateResponse(): RevokeCertificateResponse {
  return { certificate: undefined };
}

export const RevokeCertificateResponse: MessageFns<RevokeCertificateResponse> = {
  encode(message: RevokeCertificateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.certificate !== undefined) {
      CertificateMetadata.encode(message.certificate, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RevokeCertificateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRevokeCertificateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.certificate = CertificateMetadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RevokeCertificateResponse {
    return { certificate: isSet(object.certificate) ? CertificateMetadata.fromJSON(object.certificate) : undefined };
  },

  toJSON(message: RevokeCertificateResponse): unknown {
    const obj: any = {};
    if (message.certificate !== undefined) {
      obj.certificate = CertificateMetadata.toJSON(message.certificate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RevokeCertificateResponse>, I>>(base?: I): RevokeCertificateResponse {
    return RevokeCertificateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RevokeCertificateResponse>, I>>(object: I): RevokeCertificateResponse {
    const message = createBaseRevokeCertificateResponse();
    message.certificate = (object.certificate !== undefined && object.certificate !== null)
      ? CertificateMetadata.fromPartial(object.certificate)
      : undefined;
    return message;
  },
};

/**
 * CAService owns the X.509 certificate lifecycle and is the single source of
 * truth for client public keys, certificate validity, and revocation status.
 */
export type CAServiceService = typeof CAServiceService;
export const CAServiceService = {
  /** Registers a user certificate from a CSR after proof-of-possession checks. */
  registerUser: {
    path: "/ca.CAService/RegisterUser" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RegisterUserRequest): Buffer => Buffer.from(RegisterUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RegisterUserRequest => RegisterUserRequest.decode(value),
    responseSerialize: (value: RegisterUserResponse): Buffer =>
      Buffer.from(RegisterUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RegisterUserResponse => RegisterUserResponse.decode(value),
  },
  /**
   * Verifies a certificate by serial number and returns status, validity, and
   * public key material needed by KDC/Bank callers.
   */
  verifyCertificate: {
    path: "/ca.CAService/VerifyCertificate" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: VerifyCertificateRequest): Buffer =>
      Buffer.from(VerifyCertificateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): VerifyCertificateRequest => VerifyCertificateRequest.decode(value),
    responseSerialize: (value: VerifyCertificateResponse): Buffer =>
      Buffer.from(VerifyCertificateResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): VerifyCertificateResponse => VerifyCertificateResponse.decode(value),
  },
  /**
   * Deprecated compatibility lookup. New KDC/Bank code should use VerifyCertificate.
   *
   * @deprecated
   */
  getCertificate: {
    path: "/ca.CAService/GetCertificate" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetCertificateRequest): Buffer =>
      Buffer.from(GetCertificateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetCertificateRequest => GetCertificateRequest.decode(value),
    responseSerialize: (value: GetCertificateResponse): Buffer =>
      Buffer.from(GetCertificateResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetCertificateResponse => GetCertificateResponse.decode(value),
  },
  /**
   * Deprecated compatibility status check. New KDC/Bank code should use VerifyCertificate.
   *
   * @deprecated
   */
  checkRevocation: {
    path: "/ca.CAService/CheckRevocation" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CheckRevocationRequest): Buffer =>
      Buffer.from(CheckRevocationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CheckRevocationRequest => CheckRevocationRequest.decode(value),
    responseSerialize: (value: CheckRevocationResponse): Buffer =>
      Buffer.from(CheckRevocationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CheckRevocationResponse => CheckRevocationResponse.decode(value),
  },
  /** Admin dashboard list/search. */
  listCertificates: {
    path: "/ca.CAService/ListCertificates" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListCertificatesRequest): Buffer =>
      Buffer.from(ListCertificatesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListCertificatesRequest => ListCertificatesRequest.decode(value),
    responseSerialize: (value: ListCertificatesResponse): Buffer =>
      Buffer.from(ListCertificatesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListCertificatesResponse => ListCertificatesResponse.decode(value),
  },
  /** Admin dashboard detail view. This records an audit event in CA Service. */
  getCertificateDetail: {
    path: "/ca.CAService/GetCertificateDetail" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetCertificateDetailRequest): Buffer =>
      Buffer.from(GetCertificateDetailRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetCertificateDetailRequest => GetCertificateDetailRequest.decode(value),
    responseSerialize: (value: GetCertificateDetailResponse): Buffer =>
      Buffer.from(GetCertificateDetailResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetCertificateDetailResponse => GetCertificateDetailResponse.decode(value),
  },
  /** Admin dashboard revoke action. */
  revokeCertificate: {
    path: "/ca.CAService/RevokeCertificate" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RevokeCertificateRequest): Buffer =>
      Buffer.from(RevokeCertificateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RevokeCertificateRequest => RevokeCertificateRequest.decode(value),
    responseSerialize: (value: RevokeCertificateResponse): Buffer =>
      Buffer.from(RevokeCertificateResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RevokeCertificateResponse => RevokeCertificateResponse.decode(value),
  },
} as const;

export interface CAServiceServer extends UntypedServiceImplementation {
  /** Registers a user certificate from a CSR after proof-of-possession checks. */
  registerUser: handleUnaryCall<RegisterUserRequest, RegisterUserResponse>;
  /**
   * Verifies a certificate by serial number and returns status, validity, and
   * public key material needed by KDC/Bank callers.
   */
  verifyCertificate: handleUnaryCall<VerifyCertificateRequest, VerifyCertificateResponse>;
  /**
   * Deprecated compatibility lookup. New KDC/Bank code should use VerifyCertificate.
   *
   * @deprecated
   */
  getCertificate: handleUnaryCall<GetCertificateRequest, GetCertificateResponse>;
  /**
   * Deprecated compatibility status check. New KDC/Bank code should use VerifyCertificate.
   *
   * @deprecated
   */
  checkRevocation: handleUnaryCall<CheckRevocationRequest, CheckRevocationResponse>;
  /** Admin dashboard list/search. */
  listCertificates: handleUnaryCall<ListCertificatesRequest, ListCertificatesResponse>;
  /** Admin dashboard detail view. This records an audit event in CA Service. */
  getCertificateDetail: handleUnaryCall<GetCertificateDetailRequest, GetCertificateDetailResponse>;
  /** Admin dashboard revoke action. */
  revokeCertificate: handleUnaryCall<RevokeCertificateRequest, RevokeCertificateResponse>;
}

export interface CAServiceClient extends Client {
  /** Registers a user certificate from a CSR after proof-of-possession checks. */
  registerUser(
    request: RegisterUserRequest,
    callback: (error: ServiceError | null, response: RegisterUserResponse) => void,
  ): ClientUnaryCall;
  registerUser(
    request: RegisterUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RegisterUserResponse) => void,
  ): ClientUnaryCall;
  registerUser(
    request: RegisterUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RegisterUserResponse) => void,
  ): ClientUnaryCall;
  /**
   * Verifies a certificate by serial number and returns status, validity, and
   * public key material needed by KDC/Bank callers.
   */
  verifyCertificate(
    request: VerifyCertificateRequest,
    callback: (error: ServiceError | null, response: VerifyCertificateResponse) => void,
  ): ClientUnaryCall;
  verifyCertificate(
    request: VerifyCertificateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: VerifyCertificateResponse) => void,
  ): ClientUnaryCall;
  verifyCertificate(
    request: VerifyCertificateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: VerifyCertificateResponse) => void,
  ): ClientUnaryCall;
  /**
   * Deprecated compatibility lookup. New KDC/Bank code should use VerifyCertificate.
   *
   * @deprecated
   */
  getCertificate(
    request: GetCertificateRequest,
    callback: (error: ServiceError | null, response: GetCertificateResponse) => void,
  ): ClientUnaryCall;
  getCertificate(
    request: GetCertificateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetCertificateResponse) => void,
  ): ClientUnaryCall;
  getCertificate(
    request: GetCertificateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetCertificateResponse) => void,
  ): ClientUnaryCall;
  /**
   * Deprecated compatibility status check. New KDC/Bank code should use VerifyCertificate.
   *
   * @deprecated
   */
  checkRevocation(
    request: CheckRevocationRequest,
    callback: (error: ServiceError | null, response: CheckRevocationResponse) => void,
  ): ClientUnaryCall;
  checkRevocation(
    request: CheckRevocationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CheckRevocationResponse) => void,
  ): ClientUnaryCall;
  checkRevocation(
    request: CheckRevocationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CheckRevocationResponse) => void,
  ): ClientUnaryCall;
  /** Admin dashboard list/search. */
  listCertificates(
    request: ListCertificatesRequest,
    callback: (error: ServiceError | null, response: ListCertificatesResponse) => void,
  ): ClientUnaryCall;
  listCertificates(
    request: ListCertificatesRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListCertificatesResponse) => void,
  ): ClientUnaryCall;
  listCertificates(
    request: ListCertificatesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListCertificatesResponse) => void,
  ): ClientUnaryCall;
  /** Admin dashboard detail view. This records an audit event in CA Service. */
  getCertificateDetail(
    request: GetCertificateDetailRequest,
    callback: (error: ServiceError | null, response: GetCertificateDetailResponse) => void,
  ): ClientUnaryCall;
  getCertificateDetail(
    request: GetCertificateDetailRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetCertificateDetailResponse) => void,
  ): ClientUnaryCall;
  getCertificateDetail(
    request: GetCertificateDetailRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetCertificateDetailResponse) => void,
  ): ClientUnaryCall;
  /** Admin dashboard revoke action. */
  revokeCertificate(
    request: RevokeCertificateRequest,
    callback: (error: ServiceError | null, response: RevokeCertificateResponse) => void,
  ): ClientUnaryCall;
  revokeCertificate(
    request: RevokeCertificateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RevokeCertificateResponse) => void,
  ): ClientUnaryCall;
  revokeCertificate(
    request: RevokeCertificateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RevokeCertificateResponse) => void,
  ): ClientUnaryCall;
}

export const CAServiceClient = makeGenericClientConstructor(CAServiceService, "ca.CAService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): CAServiceClient;
  service: typeof CAServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
