syntax = "proto3";
package kdc;
option go_package = "mini-banking/kdc-service/internal/grpc/pb;kdcpb";

/**
 * @title KDC Service (Key Distribution Center)
 * @author Tran Nguyen Tri Thanh (tntt)
 * @summary Processing AS Exchange and TGS Exchange using a Kerberos hybrid model.
 */
service KDCService {
  /**
   * @description Phase 2: AS Exchange — Client authenticates and receives a Ticket-Granting Ticket (TGT).
   * @param {ASRequest} request - Contains client ID, target TGS ID, and parameters to prevent replay attacks.
   * @returns {ASResponse} Encrypted payload containing the Session Key and the TGT.
   */
  rpc RequestTGT(ASRequest) returns (ASResponse);

  /**
   * @description Phase 3: TGS Exchange — Client uses the TGT to request a Service Ticket for a specific service.
   * @param {TGSRequest} request - Contains the target service ID, the TGT, and the client's authenticator.
   * @returns {TGSResponse} Encrypted payload containing the Service Ticket and the Client-Service Session Key.
   */
  rpc RequestServiceTicket(TGSRequest) returns (TGSResponse);
}

    ///////////////////////////////////////////////////////////////
    //                       AS Exchange
    ///////////////////////////////////////////////////////////////

/**
 * @description Request payload for the Authentication Service (AS) Exchange.
 */
message ASRequest {
  string client_id = 1;
  string tgs_id = 2;
  bytes nonce1 = 3;
  int64 timestamp = 4;
  string cert_sn = 5;
  bytes  pre_auth_signature = 6;
}

/**
 * @description Response payload for the Authentication Service (AS) Exchange.
 * @note AS_REP = E_{pub_c}[ K_{c,tgs} || TGT || Nonce1 || TS ]
 * @note TGT = E_{K_tgs}[ client_id, client_ip, K_{c,tgs}, expiry ]
 * @note TTL default is 30 minutes
 */
message ASResponse {
  bytes encrypted_payload = 1;
  int64 tgt_expiry_unix = 2;
}

    ///////////////////////////////////////////////////////////////
    //                       TGS Exchange
    ///////////////////////////////////////////////////////////////

/**
 * @description Request payload for the Ticket-Granting Service (TGS) Exchange.
 * @note Auth_c = E_{K_{c,tgs}}[ client_id, TS, Nonce2 ]
 */
message TGSRequest {
  string service_id = 1;
  bytes tgt_ciphertext = 2;
  bytes authenticator = 3;
  string cert_sn = 4;
  bytes nonce2 = 5;
  string requested_scope = 6;
}

/**
 * @description Response payload for the Ticket-Granting Service (TGS) Exchange.
 * @note TGS_REP = E_{K_{c,tgs}}[ K_{c,v} || Ticket_v || Nonce2 ]
 * @note Ticket_v = E_{K_v}[ client_id, K_{c,v}, pub_c_pem, expiry ]
 */
message TGSResponse {
  bytes encrypted_payload = 1;
  int64 ticket_expiry_unix = 2;
}