// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ca.proto

package capb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// @description Certificate's status enum
type CertStatus int32

const (
	CertStatus_CERT_STATUS_UNKNOWN CertStatus = 0
	CertStatus_CERT_STATUS_VALID   CertStatus = 1
	CertStatus_CERT_STATUS_REVOKED CertStatus = 2
	CertStatus_CERT_STATUS_EXPIRED CertStatus = 3
)

// Enum value maps for CertStatus.
var (
	CertStatus_name = map[int32]string{
		0: "CERT_STATUS_UNKNOWN",
		1: "CERT_STATUS_VALID",
		2: "CERT_STATUS_REVOKED",
		3: "CERT_STATUS_EXPIRED",
	}
	CertStatus_value = map[string]int32{
		"CERT_STATUS_UNKNOWN": 0,
		"CERT_STATUS_VALID":   1,
		"CERT_STATUS_REVOKED": 2,
		"CERT_STATUS_EXPIRED": 3,
	}
)

func (x CertStatus) Enum() *CertStatus {
	p := new(CertStatus)
	*p = x
	return p
}

func (x CertStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ca_proto_enumTypes[0].Descriptor()
}

func (CertStatus) Type() protoreflect.EnumType {
	return &file_ca_proto_enumTypes[0]
}

func (x CertStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertStatus.Descriptor instead.
func (CertStatus) EnumDescriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{0}
}

// *
// @description Request payload for user registration and certificate issuance.
type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrPem        string                 `protobuf:"bytes,1,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_ca_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *RegisterUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// *
// @description Response payload containing the newly issued X.509 certificate.
type RegisterUserResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertificatePem string                 `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	SerialNumber   string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	NotAfterUnix   int64                  `protobuf:"varint,3,opt,name=not_after_unix,json=notAfterUnix,proto3" json:"not_after_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_ca_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *RegisterUserResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *RegisterUserResponse) GetNotAfterUnix() int64 {
	if x != nil {
		return x.NotAfterUnix
	}
	return 0
}

// *
// @description Request payload to fetch a certificate by its serial number.
type GetCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateRequest) Reset() {
	*x = GetCertificateRequest{}
	mi := &file_ca_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateRequest) ProtoMessage() {}

func (x *GetCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{2}
}

func (x *GetCertificateRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

// *
// @description Response payload containing the requested certificate and its status.
type GetCertificateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertificatePem string                 `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status         CertStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=ca.CertStatus" json:"status,omitempty"`
	NotAfterUnix   int64                  `protobuf:"varint,4,opt,name=not_after_unix,json=notAfterUnix,proto3" json:"not_after_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCertificateResponse) Reset() {
	*x = GetCertificateResponse{}
	mi := &file_ca_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateResponse) ProtoMessage() {}

func (x *GetCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{3}
}

func (x *GetCertificateResponse) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *GetCertificateResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCertificateResponse) GetStatus() CertStatus {
	if x != nil {
		return x.Status
	}
	return CertStatus_CERT_STATUS_UNKNOWN
}

func (x *GetCertificateResponse) GetNotAfterUnix() int64 {
	if x != nil {
		return x.NotAfterUnix
	}
	return 0
}

// *
// @description Request payload to check the revocation status of a certificate.
type CheckRevocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRevocationRequest) Reset() {
	*x = CheckRevocationRequest{}
	mi := &file_ca_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRevocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRevocationRequest) ProtoMessage() {}

func (x *CheckRevocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRevocationRequest.ProtoReflect.Descriptor instead.
func (*CheckRevocationRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{4}
}

func (x *CheckRevocationRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

// *
// @description Response payload indicating the current status of the certificate.
type CheckRevocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CertStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=ca.CertStatus" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RevokedAt     int64                  `protobuf:"varint,3,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRevocationResponse) Reset() {
	*x = CheckRevocationResponse{}
	mi := &file_ca_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRevocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRevocationResponse) ProtoMessage() {}

func (x *CheckRevocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRevocationResponse.ProtoReflect.Descriptor instead.
func (*CheckRevocationResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{5}
}

func (x *CheckRevocationResponse) GetStatus() CertStatus {
	if x != nil {
		return x.Status
	}
	return CertStatus_CERT_STATUS_UNKNOWN
}

func (x *CheckRevocationResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckRevocationResponse) GetRevokedAt() int64 {
	if x != nil {
		return x.RevokedAt
	}
	return 0
}

// *
// @description Request payload to revoke an active certificate.
type RevokeCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertificateRequest) Reset() {
	*x = RevokeCertificateRequest{}
	mi := &file_ca_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertificateRequest) ProtoMessage() {}

func (x *RevokeCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertificateRequest.ProtoReflect.Descriptor instead.
func (*RevokeCertificateRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeCertificateRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *RevokeCertificateRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// *
// @description No success field - failures are returned via gRPC Status Codes:
// @note codes.NotFound if the serial does not exist
// @note codes.PermissionDenied if lacking permissions
// @note codes.AlreadyExists if the cert was already revoked
type RevokeCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertificateResponse) Reset() {
	*x = RevokeCertificateResponse{}
	mi := &file_ca_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertificateResponse) ProtoMessage() {}

func (x *RevokeCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertificateResponse.ProtoReflect.Descriptor instead.
func (*RevokeCertificateResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{7}
}

var File_ca_proto protoreflect.FileDescriptor

const file_ca_proto_rawDesc = "" +
	"\n" +
	"\bca.proto\x12\x02ca\"G\n" +
	"\x13RegisterUserRequest\x12\x17\n" +
	"\acsr_pem\x18\x01 \x01(\tR\x06csrPem\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x8a\x01\n" +
	"\x14RegisterUserResponse\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\tR\x0ecertificatePem\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12$\n" +
	"\x0enot_after_unix\x18\x03 \x01(\x03R\fnotAfterUnix\"<\n" +
	"\x15GetCertificateRequest\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\"\xa8\x01\n" +
	"\x16GetCertificateResponse\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\tR\x0ecertificatePem\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12&\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0e.ca.CertStatusR\x06status\x12$\n" +
	"\x0enot_after_unix\x18\x04 \x01(\x03R\fnotAfterUnix\"=\n" +
	"\x16CheckRevocationRequest\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\"x\n" +
	"\x17CheckRevocationResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.ca.CertStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\x03 \x01(\x03R\trevokedAt\"W\n" +
	"\x18RevokeCertificateRequest\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x1b\n" +
	"\x19RevokeCertificateResponse*n\n" +
	"\n" +
	"CertStatus\x12\x17\n" +
	"\x13CERT_STATUS_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11CERT_STATUS_VALID\x10\x01\x12\x17\n" +
	"\x13CERT_STATUS_REVOKED\x10\x02\x12\x17\n" +
	"\x13CERT_STATUS_EXPIRED\x10\x032\xb5\x02\n" +
	"\tCAService\x12A\n" +
	"\fRegisterUser\x12\x17.ca.RegisterUserRequest\x1a\x18.ca.RegisterUserResponse\x12G\n" +
	"\x0eGetCertificate\x12\x19.ca.GetCertificateRequest\x1a\x1a.ca.GetCertificateResponse\x12J\n" +
	"\x0fCheckRevocation\x12\x1a.ca.CheckRevocationRequest\x1a\x1b.ca.CheckRevocationResponse\x12P\n" +
	"\x11RevokeCertificate\x12\x1c.ca.RevokeCertificateRequest\x1a\x1d.ca.RevokeCertificateResponseB/Z-mini-banking/ca-service/internal/grpc/pb;capbb\x06proto3"

var (
	file_ca_proto_rawDescOnce sync.Once
	file_ca_proto_rawDescData []byte
)

func file_ca_proto_rawDescGZIP() []byte {
	file_ca_proto_rawDescOnce.Do(func() {
		file_ca_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ca_proto_rawDesc), len(file_ca_proto_rawDesc)))
	})
	return file_ca_proto_rawDescData
}

var file_ca_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ca_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ca_proto_goTypes = []any{
	(CertStatus)(0),                   // 0: ca.CertStatus
	(*RegisterUserRequest)(nil),       // 1: ca.RegisterUserRequest
	(*RegisterUserResponse)(nil),      // 2: ca.RegisterUserResponse
	(*GetCertificateRequest)(nil),     // 3: ca.GetCertificateRequest
	(*GetCertificateResponse)(nil),    // 4: ca.GetCertificateResponse
	(*CheckRevocationRequest)(nil),    // 5: ca.CheckRevocationRequest
	(*CheckRevocationResponse)(nil),   // 6: ca.CheckRevocationResponse
	(*RevokeCertificateRequest)(nil),  // 7: ca.RevokeCertificateRequest
	(*RevokeCertificateResponse)(nil), // 8: ca.RevokeCertificateResponse
}
var file_ca_proto_depIdxs = []int32{
	0, // 0: ca.GetCertificateResponse.status:type_name -> ca.CertStatus
	0, // 1: ca.CheckRevocationResponse.status:type_name -> ca.CertStatus
	1, // 2: ca.CAService.RegisterUser:input_type -> ca.RegisterUserRequest
	3, // 3: ca.CAService.GetCertificate:input_type -> ca.GetCertificateRequest
	5, // 4: ca.CAService.CheckRevocation:input_type -> ca.CheckRevocationRequest
	7, // 5: ca.CAService.RevokeCertificate:input_type -> ca.RevokeCertificateRequest
	2, // 6: ca.CAService.RegisterUser:output_type -> ca.RegisterUserResponse
	4, // 7: ca.CAService.GetCertificate:output_type -> ca.GetCertificateResponse
	6, // 8: ca.CAService.CheckRevocation:output_type -> ca.CheckRevocationResponse
	8, // 9: ca.CAService.RevokeCertificate:output_type -> ca.RevokeCertificateResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ca_proto_init() }
func file_ca_proto_init() {
	if File_ca_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ca_proto_rawDesc), len(file_ca_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ca_proto_goTypes,
		DependencyIndexes: file_ca_proto_depIdxs,
		EnumInfos:         file_ca_proto_enumTypes,
		MessageInfos:      file_ca_proto_msgTypes,
	}.Build()
	File_ca_proto = out.File
	file_ca_proto_goTypes = nil
	file_ca_proto_depIdxs = nil
}
