// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: kdc.proto

package kdcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KDCService_RequestTGT_FullMethodName           = "/kdc.KDCService/RequestTGT"
	KDCService_RequestServiceTicket_FullMethodName = "/kdc.KDCService/RequestServiceTicket"
	KDCService_ListAuditEvents_FullMethodName      = "/kdc.KDCService/ListAuditEvents"
	KDCService_VerifyAuditChain_FullMethodName     = "/kdc.KDCService/VerifyAuditChain"
)

// KDCServiceClient is the client API for KDCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KDCService implements the Kerberos-like AS and TGS exchanges.
type KDCServiceClient interface {
	RequestTGT(ctx context.Context, in *ASRequest, opts ...grpc.CallOption) (*ASResponse, error)
	RequestServiceTicket(ctx context.Context, in *TGSRequest, opts ...grpc.CallOption) (*TGSResponse, error)
	// Admin dashboard read-only key-issuance audit log. Trust boundary: this RPC
	// is only reachable on the internal TLS gRPC network; admin authn/authz is
	// enforced by the API Gateway before it forwards the call.
	ListAuditEvents(ctx context.Context, in *ListAuditEventsRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error)
	// Replays the audit hash chain and reports the first tampering, if any.
	VerifyAuditChain(ctx context.Context, in *VerifyAuditChainRequest, opts ...grpc.CallOption) (*VerifyAuditChainResponse, error)
}

type kDCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKDCServiceClient(cc grpc.ClientConnInterface) KDCServiceClient {
	return &kDCServiceClient{cc}
}

func (c *kDCServiceClient) RequestTGT(ctx context.Context, in *ASRequest, opts ...grpc.CallOption) (*ASResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ASResponse)
	err := c.cc.Invoke(ctx, KDCService_RequestTGT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kDCServiceClient) RequestServiceTicket(ctx context.Context, in *TGSRequest, opts ...grpc.CallOption) (*TGSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TGSResponse)
	err := c.cc.Invoke(ctx, KDCService_RequestServiceTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kDCServiceClient) ListAuditEvents(ctx context.Context, in *ListAuditEventsRequest, opts ...grpc.CallOption) (*ListAuditEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditEventsResponse)
	err := c.cc.Invoke(ctx, KDCService_ListAuditEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kDCServiceClient) VerifyAuditChain(ctx context.Context, in *VerifyAuditChainRequest, opts ...grpc.CallOption) (*VerifyAuditChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAuditChainResponse)
	err := c.cc.Invoke(ctx, KDCService_VerifyAuditChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KDCServiceServer is the server API for KDCService service.
// All implementations must embed UnimplementedKDCServiceServer
// for forward compatibility.
//
// KDCService implements the Kerberos-like AS and TGS exchanges.
type KDCServiceServer interface {
	RequestTGT(context.Context, *ASRequest) (*ASResponse, error)
	RequestServiceTicket(context.Context, *TGSRequest) (*TGSResponse, error)
	// Admin dashboard read-only key-issuance audit log. Trust boundary: this RPC
	// is only reachable on the internal TLS gRPC network; admin authn/authz is
	// enforced by the API Gateway before it forwards the call.
	ListAuditEvents(context.Context, *ListAuditEventsRequest) (*ListAuditEventsResponse, error)
	// Replays the audit hash chain and reports the first tampering, if any.
	VerifyAuditChain(context.Context, *VerifyAuditChainRequest) (*VerifyAuditChainResponse, error)
	mustEmbedUnimplementedKDCServiceServer()
}

// UnimplementedKDCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKDCServiceServer struct{}

func (UnimplementedKDCServiceServer) RequestTGT(context.Context, *ASRequest) (*ASResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestTGT not implemented")
}
func (UnimplementedKDCServiceServer) RequestServiceTicket(context.Context, *TGSRequest) (*TGSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestServiceTicket not implemented")
}
func (UnimplementedKDCServiceServer) ListAuditEvents(context.Context, *ListAuditEventsRequest) (*ListAuditEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditEvents not implemented")
}
func (UnimplementedKDCServiceServer) VerifyAuditChain(context.Context, *VerifyAuditChainRequest) (*VerifyAuditChainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAuditChain not implemented")
}
func (UnimplementedKDCServiceServer) mustEmbedUnimplementedKDCServiceServer() {}
func (UnimplementedKDCServiceServer) testEmbeddedByValue()                    {}

// UnsafeKDCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KDCServiceServer will
// result in compilation errors.
type UnsafeKDCServiceServer interface {
	mustEmbedUnimplementedKDCServiceServer()
}

func RegisterKDCServiceServer(s grpc.ServiceRegistrar, srv KDCServiceServer) {
	// If the following call panics, it indicates UnimplementedKDCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KDCService_ServiceDesc, srv)
}

func _KDCService_RequestTGT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ASRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KDCServiceServer).RequestTGT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KDCService_RequestTGT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KDCServiceServer).RequestTGT(ctx, req.(*ASRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KDCService_RequestServiceTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TGSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KDCServiceServer).RequestServiceTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KDCService_RequestServiceTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KDCServiceServer).RequestServiceTicket(ctx, req.(*TGSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KDCService_ListAuditEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KDCServiceServer).ListAuditEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KDCService_ListAuditEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KDCServiceServer).ListAuditEvents(ctx, req.(*ListAuditEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KDCService_VerifyAuditChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAuditChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KDCServiceServer).VerifyAuditChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KDCService_VerifyAuditChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KDCServiceServer).VerifyAuditChain(ctx, req.(*VerifyAuditChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KDCService_ServiceDesc is the grpc.ServiceDesc for KDCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KDCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kdc.KDCService",
	HandlerType: (*KDCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestTGT",
			Handler:    _KDCService_RequestTGT_Handler,
		},
		{
			MethodName: "RequestServiceTicket",
			Handler:    _KDCService_RequestServiceTicket_Handler,
		},
		{
			MethodName: "ListAuditEvents",
			Handler:    _KDCService_ListAuditEvents_Handler,
		},
		{
			MethodName: "VerifyAuditChain",
			Handler:    _KDCService_VerifyAuditChain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kdc.proto",
}
